### ISSUE TITLE
Option for fish's default theme

### ISSUE THREAD

**Issue by ifonefox** [bpinto/oh-my-fish#147]
Unless I'm missing something, once I change fish's theme to a custom one, I cannot change it back to the vanilla fish theme. I've tried loading a blank theme, but that doesn't bring it back either. Changing it via fish_config doesn't work too. Right now, the only way is to manually copy the theme, and create a custom theme out of it. It would be nice if there was an easier way to change the theme to any of fish's included themes.

**Comment by bucaran** [comment]
If anyone feels the need to reopen this issue, please do so, I will be closing this as I see it going nowhere in the near future.
