### ISSUE TITLE
rvm.fish does not clear rvm-related vars when rvm does

### ISSUE THREAD

**Issue by develop7** [bpinto/oh-my-fish#178]
repro:

0. install system ruby (with package manager) and some ruby with rvm (i.e. 2.1)
1. run `rvm use 2.1`. `echo $GEM_HOME` will say something like `/home/user/.rvm/gems/ruby-2.1.2`
2. run `rvm use system`
3. run `echo $GEM_HOME`

expected: empty value

instead: same as before, `/home/user/.rvm/gems/ruby-2.1.2`

**Comment by bpinto** [comment]
This is stalled.

P.S.: RVM users, switch to rbenv or chruby. :P
