### ISSUE TITLE
Vundle style plugins

### ISSUE THREAD

**Issue by rominf** [bpinto/oh-my-fish#259]
It would be great to have the ability to install plugins just like in [vunlde](https://github.com/gmarik/Vundle.vim).

Current approach (all plugins are in the main repo) makes development really slow.

Yes, vunlde's approach has some issues:
1. It should be implemented. I think that it would take 100-200 LOC, because fish is more powerful than vimscript. See https://www.openhub.net/p/vundle
2. Big overhead (one file vs one file + git repo).

But I think that this worth to do.

Related to #88, #96

**Comment by bucaran** [comment]
So in this _open_ model, oh-my-fish would not have more than a very few _out of the box_ plugins and simply provide the habitat where fish would live and thrive with adequate oxygen levels, tolerable temperature, food and hiding places.

**Comment by bpinto** [comment]
At this moment, I don't intend to open plugins to any git url. I don't think it's the right time to have this.

What I think is the best approach is to convert oh-my-fish into a organization and have multiple repositories inside this organization, one for each plugin, and give permission for plugin authors to manage their own plugin repo.

This way, we would just need to change `import` to fetch the files from another repo if they do not exist locally.

**Comment by bucaran** [comment]
:+1: Cool. Let's do it one of these days. We will need a very cool logo for oh-my-fish.

**Comment by bpinto** [comment]
:+1: 

It would be awesome to have a logo for oh-my-fish, but it's beyond my skills to create one. :P

**Comment by bucaran** [comment]
> At this moment, I don't intend to open plugins to any git url. I don't think it's the right time to have this.

:+1: 

> What I think is the best approach is to convert oh-my-fish into a organization and have multiple repositories inside this organization...

We could start creating the organization, migrating the repository and taking it from there. 

I will open a new issue with this so that @bpinto can take a look when he's back.

**Comment by bpinto** [comment]
I have started working on this issue here: https://github.com/bpinto/oh-my-fish/pull/462

**Comment by bucaran** [comment]
:+1: :+1:

**Comment by bpinto** [comment]
The initial implementation #462 was merged to master. Next step is to move all plugins and themes to the [oh-my-fish organization](https://github.com/oh-my-fish).

**Comment by bpinto** [comment]
ping @rominf @samvv

**Comment by rominf** [comment]
I've commented `fish` function. In general, it looks good for the first implementation. Of course, `remove`, `list` and other options are important for future versions.

**Comment by bpinto** [comment]
Thanks! I'm already working on `list`. `remove` should come next.
