### ISSUE TITLE
What is your reload strategy?

### ISSUE THREAD

**Issue by bucaran** [bpinto/oh-my-fish#293]
I often reload `oh-my-fish` during shell sessions while testing plugins/themes, etc., and I was wondering what your strategy may be.

Sometimes I simply `⌘ Q` and reopen my terminal, but within a session I use a more civilized:

```fish
function ...
  # echo -n (set_color white)Loading oh-my-fish...
  . $fish_path/oh-my-fish.fish
  # echo (set_color green) ✓ (set_color normal)
end
```
So every time duty calls I just need to type `...`. This function is defined in my fish `.config` file. 

What is your approach and what do you think about adding a simple reload function to `functions/` or perhaps to the `.config` template.

```fish
function rl -d "Reload oh-my-fish"
    . $fish_path/oh-my-fish.fish
end
```

**Comment by bpinto** [comment]
I just open a new tab on iterm.

I'd call the function `reload` though. Also, I think the echo is fine.

**Comment by bucaran** [comment]
Mmm, I see, open a new tab and close the other maybe? 

`reload` is the best name of course, but it is still a lot to type, specially if you are doing this often enough, and I agree `rl` is a terrible name. Now, even if there was a `reload`, I think I would still prefer my custom `...` as I've become already used to those three dots. I wonder what do other people think?

**Comment by bobthecow** [comment]
aliases are a personal thing. keep 'em in your personal config :)

**Comment by bucaran** [comment]
:+1:

**Comment by bpinto** [comment]
@bobthecow do you think this function is necessary?

**Comment by bobthecow** [comment]
i wouldn't use it, but that doesn't mean nobody would use it :)

i might call it something like `fish_config_reload`, though. tab completion would make it not a pain to type, and that keeps from making a super common word "reserved" in OMF.

**Comment by bucaran** [comment]
:+1: for `fish_config_reload`

What about adding the function to the `config.fish` template instead?

**Comment by bpinto** [comment]
What do you mean by adding it to the template?

**Comment by bucaran** [comment]
Well, instead of adding it to `functions/`, we could add it to the `config.fish` file under `templates/`. Then it's up to users to keep it or not.

**Comment by bpinto** [comment]
Fish is fine with functions as long as they are in their own file, they
will be lazy loaded. Adding a function to `config.fish` is a bad idea.

**Comment by bucaran** [comment]
:+1:

**Comment by bpinto** [comment]
@bucaran any plans?

**Comment by bucaran** [comment]
Well, after this discussion I've sort of changed my mind. Having a reload function should be up to users and not to OMF. If you agree you can close this issue.

**Comment by bpinto** [comment]
:+1:
