### ISSUE TITLE
Sparklines for your Fish

### ISSUE THREAD

**Issue by bucaran** [bpinto/oh-my-fish#295]
## [_shark_](https://github.com/bucaran/shark)

A fish port of [spark](https://github.com/holman/spark).

## Install

```sh
git clone https://github.com/bucaran/shark
cd shark
cp shark /your/bin/shark # e.g /usr/local/bin/shark
fish -c "for i in (seq 127); random; end" | shark
```
### Summary

Parse a string or stream of characters and generate [sparklines](http://en.wikipedia.org/wiki/Sparkline) for any real positive numbers in a dataset.

```
$ shark 1 5 22 13 53
   ▁▁▃▂█
$ shark 0,30,55,80,33,150
   ▁▂▃▄▂█
$ echo 1/2/3/5/6/7/5/8/2 | shark
   ▁▂▃▅▆▇▅█▂
$ echo 9 13 5 17 1 | shark
   ▄▆▂█▁
```
I would like to adapt _shark_ for Oh-My-Fish. 

What do you think?

**Comment by bpinto** [comment]
I like the port. I don't know what you mean about adapting it for `oh-my-fish` though.

My feeling is that it would be better to add fish support for the spark tool. If they deny it, then I think adding it to oh-my-fish would be the next step.

**Comment by bucaran** [comment]
While still it is essentially a port as I have adapted the original formula, it ended diverging from the original in implementation in order to add support for more separators, garbled up input, etc.

>  If they deny it, then I think...

I know what you mean, but if you inspect Spark's [source](https://github.com/holman/spark/blob/master/spark) you will quickly discover it's quite verbose in bashisms. In other words, there is no way to add support to the _original_ spark for Fish without spawning bash itself from within a Fish wrapper and that would be slow.

Shark on the other hand was completely built using Fish, while still passing the same tests.

In order to handle piped input _shark_ must take its own process so can not be a function. So, in order to add this to OMF, the plugin should basically install / uninstall shark in the system. What do you think?

I simply keep my binaries in `/usr/local/bin/shark`, but I need to research what are the best practices for installing shell scripts.

**Comment by bpinto** [comment]
I'm unsure, not sure if it's on `oh-my-fish` scope to be a package manager.

**Comment by bucaran** [comment]
I agree OMF is not a package manager. However, shark will be useful to theme authors who want to add sparklines to their prompt, the [possibilities](https://github.com/holman/spark/wiki/Wicked-Cool-Usage) are infinite.

**Comment by bpinto** [comment]
I am open to suggestions. Probably something alike `import package/shark`

**Comment by bucaran** [comment]
What's inside `package/`? Would it be like directory with install scripts for packages?

**Comment by bpinto** [comment]
This is what I was thinking (could be a very bad thought):

`require package/shark` (require might be better) would execute a function that would check wether `shark` is in your $PATH, if not, would give you a message telling you to run `install_package shark`.

**Comment by bucaran** [comment]
I am trying to think what's so bad about this, but I don't know. Why not?

**Comment by bucaran** [comment]
A trivial, if not too ad-hoc, solution would be not adding anything to the `$PATH` and allow something like `echo 1 2 3 | $fish_pkg/shark`or `echo 1 2 3 | $pkg/shark`

**Comment by bucaran** [comment]
I like this. Perhaps someone will say a bit too naive, but I can't think what's so bad about this approach.

In the meantime, a trivial, but risk-free solution would be not adding anything to the `$PATH`, keep binaries in `$fish_path/packages` and have a global variable `$pkg` set to this path so as to allow `echo 1 2 3 | $pkg/shark`

**Comment by bpinto** [comment]
I think it's a simple way to make sure we have the package installed, and I can see this being used for more packages (we already have themes that requires some). And if the packages are not included we can do two things:

1. Show a better error message.
2. Mock the real package (not sure about the implications here) call when it's not available.

**Comment by bucaran** [comment]
```
set -l fish_tank /usr/local/share/fish-tank/tank.fish
if not test -e $fish_tank
  echo 'error: fish-tank is required to run these tests (https://github.com/terlar/fish-tank)'
  exit 1
end

source $fish_tank
```

**Comment by bpinto** [comment]
I think an error message like that would be great.

**Comment by bucaran** [comment]
Thoughts? It would make a nice plugin maybe? 

```
$ shark 0,30,55,80,33,150
   ▁▂▃▄▂█
```

**Comment by bpinto** [comment]
I was thinking about it, and I don't know what would the plugin contain. As you said we need it to be a binary file, basically to use shark, we just need to download the binary and add it to the path.

Should we handle it? What would be the plugin responsabilities?

**Comment by bucaran** [comment]
It would be more useful as a regular system utility, than a plugin. So a plugin does not really make much sense. How should oh-my-fish should handle binaries, etc? Perhaps a `get` plugin to search a central registry, `sea` or `ocean`; download and install fish binaries `nuggets`. 

```fish
get shark
Connecting to ocean registry...
Downloading `bucaran/shark`...
Installing to `usr/local/bin`..
Done ✓
```

**Comment by bpinto** [comment]
What about `brew`? `apt-get`? They handle it so nicely, plus, they are shell agnostic.
I don't think it's worth redoing what other established tools already do.

The solution I see for this is to create an external plugin and embedding shark inside of the plugin, see https://github.com/bpinto/oh-my-fish/issues/259

**Comment by bucaran** [comment]
:+1:
