### ISSUE TITLE
Now that we have tests, can we add this repo to travis?

### ISSUE THREAD

**Issue by bpinto** [bpinto/oh-my-fish#297]

**Comment by bucaran** [comment]
:+1:

**Comment by bpinto** [comment]
I know fish-tank runs on Travis, but I haven't dig into it yet. I have never used Travis before, so I don't know any options yet. Have you?

**Comment by bucaran** [comment]
Testing.

**Comment by bpinto** [comment]
Thanks! Let me know if I can help you in any way.

**Comment by bucaran** [comment]
It's done, the problem is I am debating if `import` should be changed a now a bit. You see, you need to invoke `import` at the bottom of the test spec because it will not just add the directories with `.fish` files to `$fish_function_path`, but also load all `.load` files. If you raise `import` up to the top it will fail because `run_specs` gets is immediately called by `fish-spec.load` and the test describe functions are still undefined at that point.

**Comment by bucaran** [comment]
Got it. Obviously, the tests should not run themselves. Importing the `fish-spec` test plugin (maybe we should drop that into another directory, like `lib`) will make `run_specs` available to `test_oh-my-fish.fish` which should then be responsible to begin the test suite after all the functions are defined.

**Comment by bpinto** [comment]
I would like to have the import call at the top, for sure. But I don't know how to do that.

Don't know if I would like to see a `run_specs` method being called inside each test file. If you could show me an example, that would help.

**Comment by bucaran** [comment]
You only need to call `run_specs` once after the test file loads all the functions. Starting the tests should be the responsibility of the module importing the `fish-spec` plugin. 

```fish
import plugins/fish-spec

function describe_oh_my_fish
  function before_all
  ...
  end
  ...
end

# Begin test suite.
run_specs

**Comment by bpinto** [comment]
Ah okay, having both the import and the method is good and better.

**Comment by bpinto** [comment]
I was thinking if we could use a [postexec binding](https://github.com/fish-shell/fish-shell/pull/1666) to run the tests after the file is read, but I don't think we can.

**Comment by bucaran** [comment]
Sorry for the delay. There was a sneaky bug in the test spec, but it's all clear now. See here [\#1881](https://github.com/fish-shell/fish-shell/issues/1881)

**Comment by bucaran** [comment]
DONE!

**Comment by bpinto** [comment]
This is just amazing! I think it would be easier to open multiple PRs instead of merging all these changes at once.

1. Travis addition.
2. Install script.
3. Test framework.

**Comment by bucaran** [comment]
:+1: 

Will submit new PRs soon.

**Comment by bucaran** [comment]
> Now that we have tests, can we add this repo to travis?

Done.

**Comment by bpinto** [comment]
Awesome! Thanks @bucaran
