### ISSUE TITLE
import function shouldn't add functions defined in the test folder to path

### ISSUE THREAD

**Issue by bpinto** [bpinto/oh-my-fish#299]

**Comment by bucaran** [comment]
What do you mean? `import` has no knowledge of any tests.

**Comment by bpinto** [comment]
This is in my `$fish_function_path`: `/Users/bpinto/.oh-my-fish/plugins/dpaste/tests/`.
There is no reason to add test files to this environment variable. Import could be smart about it.

**Comment by bucaran** [comment]
Ah, I see what you mean. Yes, I knew about this. How do you want to fix this?

1. Pass a list of directories that should not be added regardless of their contents to `import`.
2. Or just let `import` be smart and not add `test/` or  `tests/` directories.

**Comment by bpinto** [comment]
I would go with the second option for now. I think we don't need anything fancy atm.

**Comment by bucaran** [comment]
I'll PR this in a `fix-import` branch after I am done with tests and travis stuff.

**Comment by bpinto** [comment]
:+1:

**Comment by bpinto** [comment]
Thanks @bucaran !

**Comment by bpinto** [comment]
Thanks @bucaran !

**Comment by bucaran** [comment]
The culprit is actually `_prepend_tree`. Fixed.

**Comment by bucaran** [comment]
Let's continue over #308
