### ISSUE TITLE
Subsequent tests should run if one test fails

### ISSUE THREAD

**Issue by bpinto** [bpinto/oh-my-fish#307]
```
.oh-my-fish:run_plugins_tests_on_travis* λ ./script/run-tests.fish
...................⏎                                                                            

.oh-my-fish:run_plugins_tests_on_travis* λ ./script/run-tests.fish
.............✘
Expected/Users/bpinto/.oh-my-fish/custom
to not contain/Users/bpinto/.oh-my-fish/custom⏎
```

Note that after one test failed, other tests were not executed.

**Comment by bucaran** [comment]
You said you wanted to avoid this, so I deliberately added this functionality.

**Comment by bpinto** [comment]
I think I wasn't clear then, I think tests should be isolated, they could even run in parallel, so one test should not affect the other.

But during one test execution, if there is an error on an expect, it should halt the test execution at that point.

**Comment by bucaran** [comment]
> But during one test execution, if there is an error on an expect, it should halt the test execution at that point. But the test suite should not stop.

You mean stop that one test function, but not the other tests in the suite?

That's exactly how it was before... :laughing:

**Comment by bpinto** [comment]
Sorry about that. But I thought I had tested and it didn't work... =/

**Comment by bucaran** [comment]
Mmm, one solution would be using a global variable with an event handler tracking failed `expect` calls.

**Comment by bpinto** [comment]
I haven't thought about it yet, need to do some testing before. I'll work on it soon, but after the other issues.

**Comment by bucaran** [comment]
So, first thing, let me revert it so that test don't stop when one fails, but rather continue until the end of the suite and we can figure out a way to stop single tests if one of the `expect` calls fail.

What do you think?

**Comment by bpinto** [comment]
Sounds good!

**Comment by bucaran** [comment]
Well, I am working already on the whole thing as I realized there is an easier solution without event handlers. While at it, I discover there was a bug in the initial setup script.

**Comment by bucaran** [comment]
Where are we?
