### ISSUE TITLE
About describe_, before_, after_, it_ test functions.

### ISSUE THREAD

**Issue by bucaran** [bpinto/oh-my-fish#316]
Currently, only `it_` kind of tests are allowed to fail the suite, while `before_all`, etc., do _not_ (even if they themselves fail, as in they setting `$status` to ! 0) 

Now, that reload is working, it's easy to let not only `it_` tests fail, but just to understand the logic behind this better, why would anyone add an expect condition inside a `before_`, `after_` type of tests...?

**Comment by bpinto** [comment]
I have used expect blocks on `before_` blocks.
I am not sure if that is a good practice, but I can see its usage as making sure the tests are properly set up before running the tests.

**Comment by bucaran** [comment]
Mmmm. Another thing, I see implementing nested `describe` blocks reliably a little bit of a challenge. Do you have any thoughts?

**Comment by bpinto** [comment]
It's going to be hard. But now that we have a test suite that can validate `fish-spec` framework, I think it's a matter of spending some (read a lot) of time thinking on a solution, there are probably more important things to work on the test framework before we work on this, _I guess_.

**Comment by bucaran** [comment]
Agree. Let's make sure it works well and it's robust and then let's think about nested describe blocks. The one solution I was thinking was to retrieve all the global functions and after calling the first describe block get a diff with the new functions, rinse and repeat, either recursively or iteratively.

**Comment by bpinto** [comment]
We will have to manipulate the function names, similar to what we had to do on the `fish-spec` test, as there will be multiple functions with the same name e.g. `before_each`, possibly appending an index to its name.

**Comment by bucaran** [comment]
Let's make sure the current framework actually works and let's worry about it later.
