### ISSUE TITLE
Halts after first command

### ISSUE THREAD

**Issue by kholbekj** [bpinto/oh-my-fish#332]
Hey there, tried to enable the 'budspencer' theme in fish 2.1.0, which spat an 
`assertion failed: false function builtin_end`-error,
then grabbed the new fish through `homebrew upgrade fish --HEAD`
and tried, and now it sorta works, i get a prompt, i can enter a command, but the second i do, the next line prompt is printed, but the whole tab hangs. From there I can no longer give any input. Got a pointer on how to debug/provide better info?

**Comment by bpinto** [comment]
Same thing is happening to me. My advise is to remove code from the theme until you discover the line that is causing the shell to hang.

**Comment by kholbekj** [comment]
Brutal. I'll give it a shot.

**Comment by bpinto** [comment]
Nice! Thanks for this.

**Comment by kholbekj** [comment]
Okay, removing the Command history portion of the code seems to resolve it. So there's a start, but it also means the whole line tracking is disabled, so I'll see if i can get more specific.

**Comment by kholbekj** [comment]
Narrowed it a little more, removing https://github.com/bpinto/oh-my-fish/blob/master/themes/budspencer/fish_prompt.fish#L215
will make it not halt, but also stop changing color, and, presumably, entering the correct binde mode.

However, disabling all contents of the switch case that actually uses this doesn't seem to help at all, so I'm pretty confused.
https://github.com/bpinto/oh-my-fish/blob/master/themes/budspencer/fish_prompt.fish#L496

**Comment by kholbekj** [comment]
So it's definately fish_bind_mode being used in a way that no longer works.
Renaming that makes stuff work, but I can't get the prompt to represent the bind mode.

**Comment by bpinto** [comment]
I don't know much about this bind mode, perhaps @tannhuber can work on it?

**Comment by kholbekj** [comment]
Probably good, I've tried to figure out why it works in the syl20bnr theme, and not here - they're switching on the same thing, but even if i remove the set that makes budspencer hang, it doesn't seem to react to vi_mode change

**Comment by kholbekj** [comment]
Okay, I think there might be hope - it seems this comes from the glyph not being available in any powerline font i can find, defaulting to an OSX interpretation, which is inane enough prioritize Emoji. But I'll have to get hold of the Emoji font again to test... :+1:

**Comment by kholbekj** [comment]
Found one! Meslo for powerline has the nessecary components! Changing the readme

**Comment by tannhuber** [comment]
I'm sorry I can't reproduce it. Can you replace
```
echo -n (__budspencer_cmd_duration) (__budspencer_prompt_git_symbols) (__budspencer_prompt_pwd)
```
by
```
echo -n (__budspencer_cmd_duration) (__budspencer_prompt_git_symbols) (__budspencer_prompt_pwd) $fish_bind_mode
```
in `fish_right_prompt` (last function in `fish_right_prompt.fish`) in order to output the value of `$fish_bind_mode`?

**Comment by kholbekj** [comment]
Sure, it does
![1__fish___users_kasper__fish_](https://cloud.githubusercontent.com/assets/2786571/5854343/1594ff3c-a22d-11e4-82f9-91f9aa228f5e.png)
and then hangs.

**Comment by bpinto** [comment]
Are you using version 2.1+ of fish shell @tannhuber? I have fish installed from git.

**Comment by tannhuber** [comment]
I'm using the current git version, too: `fish, version 2.1.1-1193-g1ff9aba`. I assume something goes wrong with `__budspencer_preexec` on your system. The ` cd` command shouldn't draw a new prompt line at all. It should replace the current prompt line instead. It would be nice if you could help me with debugging because everything is fine with my system. First of all, we need to know which line causes trouble. Can you try inserting some debugging messages at the end of the Command history:
```
####################
# => Command history
####################
function __budspencer_create_cmd_hist -e fish_prompt -d 'Create command history without duplicates'
    if [ $_ = 'fish' ]
        set pcount (expr $pcount + 1)
        set -l IFS ''
        set -l cmd (echo $history[1] | fish_indent | expand -t 4)
        # Create prompt history
        set prompt_hist $prompt_hist $cmd
        # Create command history
        if not begin
                expr $cmd : '[cdms] ' >  /dev/null
                or contains $cmd $budspencer_nocmdhist
            end 
            if contains $cmd $$cmd_hist
                set -e $cmd_hist[1][(contains -i $cmd $$cmd_hist)]
            end 
            set $cmd_hist $$cmd_hist $cmd
        end 
    end 
    echo -n "### 1 ###" ### This line is for debugging.
    set fish_bind_mode insert
    echo -n "### 2 ###" ### This line is for debugging.
    echo -n \a
    echo -n "### 3 ###" ### This line is for debugging.
end
```
Then start two new shells and check the output of the commands `ls` and `cd`.

**Comment by kholbekj** [comment]
Absolutely, i'll post it asap. I'm on iTerm2, Build 2.0.0.20141103

**Comment by kholbekj** [comment]
Also, just for reference, i've commented out everything individually in the file already, the only line that i can remove to make this stop is `set fish_bind_mode insert`

**Comment by tannhuber** [comment]
I'm running linux. So, I can't check it myself with iTerm2. @bpinto: Are you using iTerm2 as well?

**Comment by kholbekj** [comment]
I think he is, we had a common iterm problem in another issue.

**Comment by kholbekj** [comment]
Just tried in terminal, still happens, so it's not just iTerm

**Comment by kholbekj** [comment]
![1__fish___users_kasper__fish_](https://cloud.githubusercontent.com/assets/2786571/5873060/b9839fc0-a2f2-11e4-810b-4eb8f9376de7.png)
![1__fish___users_kasper__fish_](https://cloud.githubusercontent.com/assets/2786571/5873065/cdd337c4-a2f2-11e4-9fad-07402c5bde7a.png)

**Comment by kholbekj** [comment]
aslo, out of curiosity, what is `\a` ?

**Comment by tannhuber** [comment]
The `\a` gives just an alert. With the visual bell function of your terminal it activates X11's urgency hint flag. Some window managers can use this information to send a notification and allow you quickly jumping to the corresponding window. For me it's very useful because I get a notification when a time-consuming job has terminated on another workspace. And there's a simple shortcut to jump to that window. Can you comment out this line in order to get sure that it doesn't affect your input?

**Comment by tannhuber** [comment]
Apart from that, your images posted above show that the command history function terminates as expected. If I understand you correctly, your terminal doesn't accept any input in this stage. So it doesn't show any character you type. Is this correct?

**Comment by kholbekj** [comment]
This is correct, the only visual change behavior i can provoke is the cursor being an empty square when the window  is not focues, and filled when the window is in focus.
Commenting out the `echo \a` does not change that.

**Comment by kholbekj** [comment]
And thanks a lot for that explanation, very nice to know

**Comment by tannhuber** [comment]
There's definitely something wrong in the pre execute function. But it's still confusing me. So in a next step I would try to debug the preexec and left prompt functions:
```
 64 ################
 65 # => Pre execute
 66 ################
 67 function __budspencer_preexec -d 'Execute after hitting <Enter> before doing anything else'
 68     echo -n "### 4 ###" ### This is for debugging.
 69     set -l cmd (commandline | sed 's|\s\+|\x1e|g')
 70     if [ $_ = 'fish' ]
 71         if [ -z $cmd[1] ]
 72             set -e cmd[1]
 73         end
 74         if [ -z $cmd[1] ]
 75             return
 76         end
 77         set -e budspencer_prompt_error[1]
 78         if not type -q $cmd[1]
 79             if [ -d $cmd[1] ]
 80                 set budspencer_prompt_error (cd $cmd[1] ^&1)
 81                 and commandline ''
 82                 commandline -f repaint
 83                 return
 84             end
 85         end
 86         switch $cmd[1]
 87         case 'c'
 88             if begin
 89                 [ (count $cmd) -gt 1 ]
 90                 and [ $cmd[2] -gt 0 ]
 91                 and [ $cmd[2] -lt $pcount ]
 92             end
 93                 commandline $prompt_hist[$cmd[2]]
 94                 echo $prompt_hist[$cmd[2]]  | xsel
 95                 commandline -f repaint
 96                 return
 97             end
 98         case 'cd'
 99             if [ (count $cmd) -le 2 ]
100                 set budspencer_prompt_error (eval $cmd ^&1)
101                 and commandline ''
102                 if [ (count $budspencer_prompt_error) -gt 1 ]
103                     set budspencer_prompt_error $budspencer_prompt_error[1]
104                 end
105                 commandline -f repaint
106                 return
107             end
108         case 'day' 'night'
109             if [ (count $cmd) -eq 1 ]
110                 eval $cmd
111                 commandline ''
112                 commandline -f repaint
113                 return
114             end
115         end
116     end
117     echo -n "### 5 ###" ### This is for debugging.
118     commandline -f execute
119     echo -n "### 6 ###" ### This is for debugging.
120 end
```
and
```
690 ###############################################################################
691 # => Left prompt
692 ###############################################################################
693 
694 function fish_prompt -d 'Write out the left prompt of the budspencer theme'
695     set -g last_status $status
696     echo -n -s (__budspencer_prompt_bindmode) (__budspencer_prompt_git_branch) (__budspencer_prompt_left_symbols) '' ' '
697     echo -n "### 7 ###"
698 end
```
Can you check `ls` and `cd` again?

**Comment by kholbekj** [comment]
![1__fish___users_kasper__fish_](https://cloud.githubusercontent.com/assets/2786571/5874260/b85cc54c-a2ff-11e4-9188-67acfc8c00ff.png)
![1__fish___users_kasper__fish_](https://cloud.githubusercontent.com/assets/2786571/5874268/c7de8140-a2ff-11e4-9648-1c8175eed417.png)
no 5 and 6, it seems

**Comment by tannhuber** [comment]
We're on the right track. I think you've overlooked the 4, haven't you? It's the first line in the preexec function (number 68 in my line numbering scheme, but might be slightly different in yours). So can you extend the preexec function again?
```
 64 ################                                                                                                          
 65 # => Pre execute
 66 ################
 67 function __budspencer_preexec -d 'Execute after hitting <Enter> before doing anything else'
 68     echo -n "### 4 ###"
 69     set -l cmd (commandline | sed 's|\s\+|\x1e|g')
 70     echo -n "### 8 ###"
 71     if [ $_ = 'fish' ]
 72         if [ -z $cmd[1] ]
 73             set -e cmd[1]
 74         end
 75     echo -n "### 9 ###"
 76     if [ $_ = 'fish' ]
 77         echo -n "### 10 ###"
 78         if [ -z $cmd[1] ]
 79             return
 80         end
 81         set -e budspencer_prompt_error[1]
 82         echo -n "### 11 ###"
 83         if not type -q $cmd[1]
 84             if [ -d $cmd[1] ]
 85                 set budspencer_prompt_error (cd $cmd[1] ^&1)
 86                 and commandline ''
 87                 commandline -f repaint
 88                 return
 89             end
 90         end
 91         echo -n "### 12 ###"
 92         switch $cmd[1]
 93         case 'c'
 94             if begin
 95                 [ (count $cmd) -gt 1 ]
 96                 and [ $cmd[2] -gt 0 ]
 97                 and [ $cmd[2] -lt $pcount ]
 98             end
 99                 commandline $prompt_hist[$cmd[2]]
100                 echo $prompt_hist[$cmd[2]]  | xsel
101                 commandline -f repaint
102                 return
103             end
104         case 'cd'
105             if [ (count $cmd) -le 2 ]
106                 set budspencer_prompt_error (eval $cmd ^&1)
107                 and commandline ''
108                 if [ (count $budspencer_prompt_error) -gt 1 ]
109                     set budspencer_prompt_error $budspencer_prompt_error[1]
110                 end
111                 commandline -f repaint
112                 return
113             end
114         case 'day' 'night'
115             if [ (count $cmd) -eq 1 ]
116                 eval $cmd
117                 commandline ''
118                 commandline -f repaint
119                 return
120             end
121         end
122     end
123     echo -n "### 5 ###"
124     commandline -f execute
125     echo -n "### 6 ###"
126 end

**Comment by tannhuber** [comment]
Please wait a moment. I've introduced another bug.

**Comment by tannhuber** [comment]
Forget the code above. Can you try this instead?
```
 64 ################
 65 # => Pre execute
 66 ################
 67 function __budspencer_preexec -d 'Execute after hitting <Enter> before doing anything else'
 68     echo -n "### 4 ###" ### This is for debugging.
 69     set -l cmd (commandline | sed 's|\s\+|\x1e|g')
 70     echo -n "### 8 ###" ### This is for debugging.
 71     if [ $_ = 'fish' ]
 72         if [ -z $cmd[1] ]
 73             set -e cmd[1]
 74         end
 75         if [ -z $cmd[1] ]
 76             return
 77         end
 78         set -e budspencer_prompt_error[1]
 79         echo -n "### 9 ###" ### This is for debugging.
 80         if not type -q $cmd[1]
 81             if [ -d $cmd[1] ]
 82                 set budspencer_prompt_error (cd $cmd[1] ^&1)
 83                 and commandline ''
 84                 commandline -f repaint
 85                 return
 86             end
 87         end
 88         echo -n "### 10 ###" ### This is for debugging.
 89         switch $cmd[1]
 90         case 'c'
 91             if begin
 92                 [ (count $cmd) -gt 1 ]
 93                 and [ $cmd[2] -gt 0 ]
 94                 and [ $cmd[2] -lt $pcount ]
 95             end
 96                 commandline $prompt_hist[$cmd[2]]
 97                 echo $prompt_hist[$cmd[2]]  | xsel
 98                 commandline -f repaint
 99                 return
100             end
101         case 'cd'
102             if [ (count $cmd) -le 2 ]
103                 set budspencer_prompt_error (eval $cmd ^&1)
104                 and commandline ''
105                 if [ (count $budspencer_prompt_error) -gt 1 ]
106                     set budspencer_prompt_error $budspencer_prompt_error[1]
107                 end
108                 commandline -f repaint
109                 return
110             end
111         case 'day' 'night'
112             if [ (count $cmd) -eq 1 ]
113                 eval $cmd
114                 commandline ''
115                 commandline -f repaint
116                 return
117             end
118         end
119     end
120     echo -n "### 5 ###" ### This is for debugging.
121     commandline -f execute
122     echo -n "### 6 ###" ### This is for debugging.
123 end
```

**Comment by tannhuber** [comment]
The `sed` command might be incompatible with your `sed` version.

**Comment by kholbekj** [comment]
On it. If you don't include the line-numbers, i can copy-paste to avoid missing something again :)

**Comment by kholbekj** [comment]
![1__fish___users_kasper__fish_](https://cloud.githubusercontent.com/assets/2786571/5876283/547cdd20-a316-11e4-89ab-9dbf9c2f9841.png)
![1__fish___users_kasper__fish_](https://cloud.githubusercontent.com/assets/2786571/5876295/65b72398-a316-11e4-85d4-7e8a25cc8bb6.png)
included ### 1-8 ### now for sure.

**Comment by kholbekj** [comment]
oh sorry, there's also 9-10, one minute

**Comment by kholbekj** [comment]
Didn't change the output, though. Still only seeign 1,2,3 and 7

**Comment by tannhuber** [comment]
Obviously the preexec function isn't executed at all. What's the output of:`bind | grep preexec`?

**Comment by kholbekj** [comment]
nothing

**Comment by tannhuber** [comment]
Okay, what says `echo $fish_key_bindings`?

**Comment by kholbekj** [comment]
fish_default_key_bindings

**Comment by kholbekj** [comment]
bind:
```
bind '' self-insert
bind \n 'commandline -f execute; vi_mode_insert'
bind \ck kill-line
bind \cy yank
bind \t complete
bind \e\n commandline\ -i\ \\n
bind \e\[A up-or-search
bind \e\[B down-or-search
bind -k down down-or-search
bind -k up up-or-search
bind \e\[C forward-char
bind \e\[D backward-char
bind -k right forward-char
bind -k left backward-char
bind -k dc delete-char
bind -k backspace backward-delete-char
bind  backward-delete-char
bind \e\[H beginning-of-line
bind \e\[F end-of-line
bind \e\[1\~ beginning-of-line
bind \e\[4\~ end-of-line
bind -k home beginning-of-line
bind -k end end-of-line
bind -k sdc backward-delete-char
bind \e\eOC nextd-or-forward-word
bind \e\eOD prevd-or-backward-word
bind \e\e\[C nextd-or-forward-word
bind \e\e\[D prevd-or-backward-word
bind \eO3C nextd-or-forward-word
bind \eO3D prevd-or-backward-word
bind \e\[3C nextd-or-forward-word
bind \e\[3D prevd-or-backward-word
bind \e\[1\;3C nextd-or-forward-word
bind \e\[1\;3D prevd-or-backward-word
bind \e\eOA history-token-search-backward
bind \e\eOB history-token-search-forward
bind \e\e\[A history-token-search-backward
bind \e\e\[B history-token-search-forward
bind \eO3A history-token-search-backward
bind \eO3B history-token-search-forward
bind \e\[3A history-token-search-backward
bind \e\[3B history-token-search-forward
bind \e\[1\;3A history-token-search-backward
bind \e\[1\;3B history-token-search-forward
bind \ca beginning-of-line
bind \ce end-of-line
bind \ey yank-pop
bind \cw backward-kill-path-component
bind \cp history-search-backward
bind \cn history-search-forward
bind \cf forward-char
bind \cb backward-char
bind \ct transpose-chars
bind \et transpose-words
bind \eu upcase-word
bind \ec capitalize-word
bind \e backward-kill-word
bind \eb backward-word
bind \ef forward-word
bind \e\[1\;5C forward-word
bind \e\[1\;5D backward-word
bind \e\[1\;9A history-token-search-backward
bind \e\[1\;9B history-token-search-forward
bind \e\[1\;9C forward-word
bind \e\[1\;9D backward-word
bind \e. history-token-search-backward
bind -k ppage beginning-of-history
bind -k npage end-of-history
bind \e\< beginning-of-buffer
bind \e\> end-of-buffer
bind \el __fish_list_current_token
bind \ew 'set tok (commandline -pt); if test $tok[1]; echo; whatis $tok[1]; commandline -f repaint; end'
bind \cl 'clear; commandline -f repaint'
bind \cc '__vi_mode_save_cmdline; for i in (seq (count (commandline))); echo; end; commandline ""; vi_mode_insert'
bind \cu backward-kill-line
bind \ed kill-word
bind \cd delete-or-exit
bind -k f1 __fish_man_page
bind \eh __fish_man_page
bind \ep __fish_paginate
bind -k btab complete-and-search
bind \e 'commandline -f backward-char; vi_mode_normal'
```

**Comment by tannhuber** [comment]
Can you `set -U fish_key_bindings fish_vi_key_bindings`?

**Comment by kholbekj** [comment]
I can, but it does not change the output, of `bind | grep preexec`, should it?

**Comment by kholbekj** [comment]
! this has a new effect! now the terminal hangs immediatly, and is yellow from the start!

**Comment by tannhuber** [comment]
Well, it should only redefine some keys:
```
if [ $fish_key_bindings = 'fish_vi_key_bindings' ]
    bind '#' __budspencer_toggle_symbols
    bind -M visual '#' __budspencer_toggle_symbols
    bind ' ' __budspencer_toggle_pwd
    bind -M visual ' ' __budspencer_toggle_pwd
    bind L __budspencer_cd_next
    bind H __budspencer_cd_prev
    bind m mark
    bind M unmark
    bind . __budspencer_edit_commandline
    bind \cv __budspencer_edit_commandline
    bind -M insert \cv __budspencer_edit_commandline
    bind -M insert \n __budspencer_preexec
    bind \n __budspencer_preexec
end
```
Can you comment out these `bind` commands and then activate them step by step? `fish_key_bindings` isn't used anywhere else. So, one of these commands must be responsible for the new freeze.

**Comment by kholbekj** [comment]
Absolutely.

**Comment by kholbekj** [comment]
Commenting out all of them did not change that it freezes immideatly

**Comment by tannhuber** [comment]
I'm totally confused. Have you already tried `fish_vi_key_bindings` with another theme?

**Comment by kholbekj** [comment]
works fine with the sylb20bnr theme, just retried.

**Comment by kholbekj** [comment]
I'm willing to do some sort of screensharing or whatnot if you want to, i imagine it's quite painful to blindly debug this.

**Comment by bpinto** [comment]
Loving this conversation folks! I am using iterm2.

P.S.: If you do a screensharing, http://appear.in is awesome.

**Comment by kholbekj** [comment]
"It's so easy it almost hurts" ok sure :)

**Comment by tannhuber** [comment]
I want to leave in a few minutes although I'm willing to fix it. For today let's say that it's important to `set -U fish_key_bindings fish_vi_key_bindings`. Does the greeting still appear? It must be enabled, of course. You can enable it with `set -e budspencer_nogreeting`.

**Comment by kholbekj** [comment]
Greeting still appears :)

**Comment by tannhuber** [comment]
Although I think the problem is in the left prompt, can you disable the right prompt by renaming `fish_right_prompt.fish` into `fish_right_prompt.fish.bak`?

**Comment by bpinto** [comment]
After running `set -U fish_key_bindings fish_vi_key_bindings`, the theme correctly works on my computer.

**Comment by tannhuber** [comment]
@bpinto Does it work without any modifications or after disabling some functionality?

**Comment by bpinto** [comment]
Without any modification, but only on vi mode. I noticed something funny
when changing from normal to insert mode but I need to do more
investigation.

**Comment by tannhuber** [comment]
Unlike written in the README, it seems that the theme doesn't work anymore with emacs mode. I didn't check emacs mode after the latest changes. I think I should modify the README as soon as it's running with @kholbekj's system.

**Comment by tannhuber** [comment]
I updated the README and made some small changes, see https://github.com/bpinto/oh-my-fish/pull/366

**Comment by bpinto** [comment]
Thanks @tannhuber
