### ISSUE TITLE
rbenv plugin issues

### ISSUE THREAD

**Issue by daenney** [bpinto/oh-my-fish#335]
I just pulled master and the second I add the `rbenv` plugin to my plugins I get this:

```
/Users/daenney/Development/github/oh-my-fish/functions/import.fish (line 32): begin; /usr/local/var/rbenv/bin/rbenv --version
                                                                                     ^
in . (source) call of file '-',
	called on line 65 of file '/Users/daenney/Development/github/oh-my-fish/functions/import.fish',

in command substitution
	called on line 39 of file '/Users/daenney/Development/github/oh-my-fish/functions/import.fish',

in . (source) call of file '/Users/daenney/Development/github/oh-my-fish/plugins/rbenv/rbenv.load',
	called on line 40 of file '/Users/daenney/Development/github/oh-my-fish/functions/import.fish',

in function 'import',
	called on line 24 of file '/Users/daenney/Development/github/oh-my-fish/oh-my-fish.fish',
	with parameter list 'plugins/brew plugins/bundler plugins/localhost plugins/rbenv plugins/python plugins/pyenv'

in . (source) call of file '/Users/daenney/Development/github/oh-my-fish/oh-my-fish.fish',
	called on line 79 of file '/Users/daenney/.config/fish/config.fish',

in . (source) call of file '/Users/daenney/.config/fish/config.fish',
	called on standard input,
```

Master is currently at 6834ae756e9bc4988e34ffbb5d662a710f413949 for me.

**Comment by bucaran** [comment]
Where is your `.rbenv` directory located?

**Comment by daenney** [comment]
I have two directories involved, `/usr/local/var/rbenv` is the stuff that contains `versions/` and `shims/`, `/usr/local/opt/rbenv` is the one that contains `bin/` etc. Looks like it's calling out to `/usr/local/var/rbenv/bin/rbenv` which doesn't exist, that should be `/usr/local/bin/rbenv` which is available on my `$PATH`.

I've set up `RBENV_ROOT` to point to `/usr/local/var/rbenv` as per Homebrew's instructions. This has always worked so far.

**Comment by bucaran** [comment]
Look at `rbenv.load`

```fish
set -l rbenv_dir "$RBENV_ROOT"
if [ ! $rbenv_dir ]
  set rbenv_dir $HOME/.rbenv
end

if [ ! -d "$rbenv_dir" ]
  echo ".rbenv directory not found."
  exit 1
end
```

I just added that last check there BTW. 

`rbenv_dir` should point to your location.

**Comment by daenney** [comment]
But that's not correct.

According to the rbenv documentation:

```
Added support for storing rbenv versions and shims in directories other than ~/.rbenv with the $RBENV_ROOT environment variable.
```

This means that `RBENV_ROOT` is supposed to be used when you want to store shims and versions in another location then where you store the rbenv binary etc. You can't do `RBENV_ROOT/bin/rbenv`.

**Comment by bucaran** [comment]
This plugin was giving trouble too when I added `import.fish` a month or so ago.

I don't have `rbenv` here, so would you mind trying this for me?

```fish
import $rbenv_dir
```

**Comment by daenney** [comment]
Where should I add that?

**Comment by bucaran** [comment]
In `rbenv.load` after 
```
set -l rbenv_dir "$RBENV_ROOT"
if [ -z "$rbenv_dir" ]
  set rbenv_dir $HOME/.rbenv
end
```

**Comment by daenney** [comment]
Nope, same problem.

The issue is that it's building up the path incorrectly when calling out to the rbenv binary.

```fish
set -l rbenv_dir "$RBENV_ROOT"
if [ ! $rbenv_dir ]
  set rbenv_dir $HOME/.rbenv
end
```

This means that if `RBENV_ROOT` is set we set the value of `rbenv_dir` to `RBENV_ROOT``, else we set it to `HOME/.rbenv`. However, that's not how it's meant to be used.

When you know do `eval $rbenv_dir/bin/rbenv --version` a few lines further down in the plugin this will blow up because `RBENV_ROOT` isn't meant to point at the location of the directory that contains the `bin/` directory.

**Comment by bucaran** [comment]
What would be the correct way to build the path?

**Comment by daenney** [comment]
I would do it this way:

* Check if `rbenv` can be found on `$PATH` and call out to that
* If not, check if `$HOME/.rbenv/bin/rbenv` exists and call that instead
* Else: fail with a message that the rbenv binary cannot be found

**Comment by bucaran** [comment]
That would be awesome.

@bpinto Remember this issue? I had a naive fix in place, but it probably got squashed away when we were working on `import`, etc.

**Comment by daenney** [comment]
Perfect. Let me whip something up. Thanks for being so responsive!

**Comment by daenney** [comment]
Do we have some kind of `find on path` function in fish?

**Comment by bucaran** [comment]
No, but there is plain ol' `find` 

```fish
find "$dir" $pattern
```

**Comment by daenney** [comment]
Eh, I meant on `$PATH`. But I guess I can just run the command and check to see it doesn't error.

**Comment by bucaran** [comment]
Use `contains`.

**Comment by bpinto** [comment]
I think the confusion is that RBENV_ROOT is being used for two things. To be honest, looking at other plugins (e.g. ndenv) we use this PLUGIN_ROOT syntax for customizing the binary location, so I think we accidentally used a variable name that rbenv uses for other purposes.

Both usages should be supported, so I suggest renaming RBENV_ROOT to something else.

**Comment by daenney** [comment]
That's what I was planning on doing, both use cases need to be supported.

**Comment by daenney** [comment]
#337 is the PR.

**Comment by bpinto** [comment]
Thanks for working on this.

**Comment by bucaran** [comment]
@bpinto @daenney As you may know, `pyenv` is a fork of `rbenv` and their setup is very similar. I submitted a PR #389 with some improvements over the current `pyenv` and would appreciate if you could take a look at it and tell me what is the current `rbenv` doing that can't be simplified to something like #389. Am I missing something?

I installed both `rbenv` and `pyenv` directly cloning their respective repositories into `$HOME` (could have been anywhere) and symlinking it into `/usr/local` which I own.
