### ISSUE TITLE
Share bash history with oh-my-fish

### ISSUE THREAD

**Issue by IslamAzab** [bpinto/oh-my-fish#336]
How do one share bash history with oh-my-fish?

**Comment by bucaran** [comment]
In bash try `echo $HISTFILE` to find out the location of your `.bash_history`.
Then from fish `cat <location>`, it should be around `~/user_name/.bash_history`

**Comment by bpinto** [comment]
What do you mean by share bash history?

**Comment by IslamAzab** [comment]
@bpinto The history of the commands I type in bash, I want them to exist to oh-my-fish too.

**Comment by bpinto** [comment]
I don't know a solution for this, better ask for help for the people that create the shell: [fish-shell](https://github.com/fish-shell/fish-shell)

I know fish and shell have different formatting for the history file, so it might not be possible.

**Comment by IslamAzab** [comment]
As @mmacedo suggested through our discussion [here] (http://michelpm.com/blog/2013/07/26/switching-from-zsh-to-fish/#disqus_thread) , it is a bad idea since they have different syntaxes also let me quote what he said 
>They are not just two shells. They use different languages. Neither is supposed to work with the other. What I did there was to execute a bash script in bash and copy the state back to fish, you can not actually execute POSIX in fish.
