### ISSUE TITLE
Need an update guide

### ISSUE THREAD

**Issue by amio** [bpinto/oh-my-fish#341]
I can `cd ~/.oh-my-fish; git pull` to update oh-my-fish, but is this a 'right' way?
or maybe there should be a script for updating?

**Comment by bpinto** [comment]
It is the right way, maybe we can make it easier.

I have considered adding a `update_oh_my_fish` function that would go to `$fish_path` and run `git pull --rebase` automatically.

It also needs to handle update in the case a person installed `oh-my-fish` without git (downloading the zip from github).

**Comment by bpinto** [comment]
Want to give me a pull request adding this feature? It would be amazing.

**Comment by bucaran** [comment]
:+1: Mmm sounds like fun.

**Comment by amio** [comment]
Let me have a try :)

**Comment by bpinto** [comment]
Let me know if I can help you with anything. :)

**Comment by amio** [comment]
Of course and thanks :)
A little busy on office working these days, so I have some thoughts but not start it yet :P

**Comment by bpinto** [comment]
No rush, I was until today too. :+1:

**Comment by bucaran** [comment]
@amio Hey how is it going? :)

**Comment by amio** [comment]
Just come back from company's yearly outing, I'll start it today or tommorrow :P

**Comment by amio** [comment]
How can I check if a git repo clean or dirty? 

```bash
# this works fine, executing in terminal
# the command return 0 when the working directory is clean
$ git status --porcelain | grep "^[ MADRC]"
?? functions/update_oh_my_fish.fish
```

```bash
# but I can't make it work inside a "if" block, I must have something misunderstood with usage of "if" or "grep" > <
  if [ (git status --porcelain | grep "^[ MADRC]") -eq 0 ]
    echo clean
  else
    echo dirty
  end
```

**Comment by bucaran** [comment]
@amio Check [this](http://stackoverflow.com/questions/5139290/how-to-check-if-theres-nothing-to-be-committed-in-the-current-branch). 

So, what exactly are you going to do? and how does a automatic update would work / look like?

What about something like?

```fish
$> update
...
Oh-My-Fish up to date.
Last commit: 580f3e1d9dc2cdc47eb4698eb80f2d572480324a
```

**Comment by amio** [comment]
I want to check if the directory is clean for `git pull`

```bash
# This should be good to updating
$ git status --porcelain
?? a-new-file.txt

# Updating should abort when meet this
$ git status --porcelain
 M a-modified-file.txt
A  a-modified-and-indexed-file.txt
D  a-deleted-and-indexed-file.txt
```

**Comment by bucaran** [comment]
If you are updating via git, just `git --pull rebase upstream master`. I don't see what's the grand benefit of checking if the repo is dirty or not.

**Comment by bpinto** [comment]
As far as I know, this is the fastest way to do it:
```
function _is_git_dirty
  echo (command git status -s --ignore-submodules=dirty ^/dev/null)
end
```

**Comment by bobthecow** [comment]
depending on what exactly you mean by "dirty", there are quite a "fastest ways" :)

https://github.com/bpinto/oh-my-fish/blob/master/themes/bobthefish/fish_prompt.fish#L284-L289

**Comment by amio** [comment]
Wow, thank you all!

@bucaran
`git ls-files` is great! I never knew that :D
Well it cannot figure out files in staging area, which could abort a `git-pull` operation:
```bash
$ git status -sb
## func-update-omf
A  functions/update_oh_my_fish.fish

$ git ls-files --other --directory --exclude-standard
# no output
```

@bpinto 
I finally figure out the `echo` append a `\n` to the end of output which cause `if [ ( _is_git_dirty ) ]` get a truthy value, so add a `-n` make it work:
```bash
function _is_git_touched
	echo -n (command git status --porcelain ^/dev/null | grep "^[ MADRCU]")
end

if [ -d .git ]
  if [ ( _is_git_touched ) ]
    git pull
  else
	# echo Do you want to overwrite local modification?
  end
end
```

@bobthecow 
Useful snippets :+1: 
I want to check if I can perform `git-pull` in the `.oh-my-fish` directory safely, so define 'dirty' as a situation that:
- If any file has flag ' MADRCU', which means modified, added, etc (according to [git-status man page](http://git-scm.com/docs/git-status))

And, if only new file present:
```bash
$ git status -s
?? a-new-file-but-not-added-to-git-staging-area.txt
```
It won't be considered as 'dirty'.

so, I made it `git status --porcelain ^/dev/null | grep "^[ MADRCU]"`, seems this works as I expected.
