### ISSUE TITLE
autojump plugin doesn't work

### ISSUE THREAD

**Issue by arcticlion** [bpinto/oh-my-fish#346]
It prompt

```
cd: The directory 'Please source the correct autojump file in your shell's' does not exist
```

So my solution is source the autojump.fish file in your fish configuration, by opening the file ~/.config/fish/config.fish in an editor and adding these lines:

```bash
# Add support autojump
if test -e /usr/local/Cellar/autojump/22.2.2/etc/autojump.fish
    . /usr/local/Cellar/autojump/22.2.2/etc/autojump.fish
end

```

Hope to fix this bug.

**Comment by bpinto** [comment]
Hey @arcticlion, thanks for the heads up. But with autojump support for fish, we have deprecated the autojump plugin, so I've actually just removed the plugin from the repo.

**Comment by arcticlion** [comment]
@bpinto The alternative solution is z?

**Comment by bpinto** [comment]
Autojump has builtin support for fish, so judging from the readme, as long as it's installed and in your path, it should work.
