### ISSUE TITLE
Some themes have no screenshots.

### ISSUE THREAD

**Issue by bucaran** [bpinto/oh-my-fish#349]
- [x] @wzhishen
- [x] @bbbenji
- [x] @JBarberU
- [x] @mtahmed
- [x] @syl20bnr

**Comment by xorgy** [comment]
For coffeeandcode

![coffeeandcode](https://cloud.githubusercontent.com/assets/1272018/5966170/e846c75e-a7f9-11e4-8aeb-ebec4c974f5b.png)

**Comment by bpinto** [comment]
Were all screenshots added?

**Comment by syl20bnr** [comment]
I'll add mine , sorry for the late reply.

Le mercredi 11 février 2015, Bruno <notifications@github.com> a écrit :

> Were all screenshots added?
> On Wed, Feb 11, 2015 at 10:51 Jorge Bucaran <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Closed #349 <https://github.com/bpinto/oh-my-fish/issues/349>.
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/bpinto/oh-my-fish/issues/349#event-233897475>.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/bpinto/oh-my-fish/issues/349#issuecomment-73878666>.
>


-- 
-syl20bnr-

**Comment by bucaran** [comment]
3 more to go.

**Comment by bbbenji** [comment]
I never made a theme:) I just submitted a bugfix for coffeeandcode but it looks like it already has a screenshot.

**Comment by amio** [comment]
How about open an "Theme Screenshots" issue, for people uploading screenshots.

one theme, one comment, one shot.
If a theme was updated, the author should modify the original comment replace it with a new shot.

And beyond a place for uploading screenshots, we have a theme gallery for fresh user to look through :D isn't that nice?

**Comment by bobthecow** [comment]
not a bad idea. or a wiki page? can you upload photos to a wiki page?

**Comment by bucaran** [comment]
> can you upload photos to a wiki page?
Yes.

@amio @bobthecow
+1 wiki 

Now, what if, we had a simple plugin to allow us to _tryout_ themes without modifying our `config.fish`. It should support auto-completions with available themes, restoring the original theme, list all themes, etc.

:sunglasses: 

## try
```
try <theme name>
        [-l --list]
        [-u --update]
        [-r --restore]
        [-h --help]

OPTIONS
  try <theme name>
    Quick switch to theme.

  try -l --list
    List available themes.

  try -u --update
    Update theme auto-completions.

  try -r --restore
    Restore original theme.

  try -h --help
    Show usage help.
```

![mov](https://cloud.githubusercontent.com/assets/8317250/6200747/9b37b712-b4c8-11e4-889f-48307ecb7f6b.gif)

**Comment by syl20bnr** [comment]
Thanks for updating the screenshots. Very nice plugin for quick try themes :+1:

**Comment by amio** [comment]
@bucaran Wonderful plugin! Exactly what I'm expecting to.

@bucaran @bobthecow I can't upload to wiki, neither dragging nor clicking the image button(just pop a dialog for me to fill image title & url).

**Comment by bucaran** [comment]
@amio If you can't add/edit the Wiki then it's probably not a setup as a public Wiki. I can't confirm, we'll have to wait for @bpinto to comment.

**Comment by amio** [comment]
I can open the wiki editor, but didn't figure out how to upload image on the wiki editor: https://github.com/bpinto/oh-my-fish/wiki/_new

**Comment by bucaran** [comment]
You should be able to just drag and drop, but there's also this button.

![img](https://cloud.githubusercontent.com/assets/8317250/6202259/27a9f30a-b522-11e4-8e9f-daa91efa954f.png)
