### ISSUE TITLE
Improve fish-spec.

### ISSUE THREAD

**Issue by bucaran** [bpinto/oh-my-fish#356]
The current state of affairs is `fish-spec`, although it works and gets the job done, still has room for improvement:

+ [x] Revise everything, find and exterminate bugs.
+ [ ] Add more conditions to spec. `--to-be-greater-than`, `--to-be`...,
+ [ ] Find out how to separate the framework from Oh-my-fish and discuss what should be done if possible.

Post here and I will expand this to-do list.

**Comment by bpinto** [comment]
I'll keep this issue open for up to 2 weeks, if nothing changes, I'll close it. :)

I don't like open issues/prs.

**Comment by bucaran** [comment]
:+1:

**Comment by bpinto** [comment]
`--to-contain-any`, `--to-not-contain-any`
`--to-be-exactly-like` (array comparison)

**Comment by bucaran** [comment]
This may not be happening anytime soon, but hey, as long as we are alive there is still a chance this issue can see the light again.

Closing for now...
