### ISSUE TITLE
Budspencer Colors Working in Tmux only?

### ISSUE THREAD

**Issue by Nekroze** [bpinto/oh-my-fish#359]
Hi,

Only just started using fish, loving it and this repo is super helpful.

I am using the budspencer theme with a git build of fish (via arch aur package `fish-shell-git`) and it is all functioning and I love it except for one minor issue that is annoying me a little more then it should.

The colors for this theme are not presenting the values I have set (solarized colors) unless i am in a tmux (TERM=screen*) session.

This is in any of my terminal emulators:
![fish-xterm](https://cloud.githubusercontent.com/assets/1460186/5996039/f3cf4476-aaeb-11e4-909c-eca01563ecdf.JPG)

However this is in any of those terminal emulators when i am running tmux:
![fish-tmux](https://cloud.githubusercontent.com/assets/1460186/5996042/03752aa8-aaec-11e4-897b-80dd24f7b91b.JPG)

As you can see the latter is what I am aiming for as the colors are all correct.

Anyone know what is going on here or if it is a bug with the theme or something?

I would greatly appreciate any assistance, thanks for your time.

**Comment by bpinto** [comment]
Your tmux configuration is probably not getting all the colors:
http://unix.stackexchange.com/questions/1045/getting-256-colors-to-work-in-tmux

I have this on my tmux.conf file:
`set -g default-terminal "screen-256color"`

**Comment by Nekroze** [comment]
Hi @bpinto,

Indeed tmux is setting term to `screen` and not `screen-256color` however the colours are displaying as i set them when it is just `screen` but if it is `screen-256color` it displays the same as the picture without tmux which is a term of `xterm-256color`.

I am setting the colors manually to solarized dark but the weird thing is they are not displaying in `*-256color` term's correctly yet paradoxically are displaying correctly otherwise.

**Comment by bpinto** [comment]
Aren't your colors correctly being displayed but you think they are not? Perhaps you need to adjust the colors for the 256 support.

**Comment by Nekroze** [comment]
I am assigning colors for the fish theme via the solarized dark hex colors, I have used these hex values for many other things on my systems and it all displays fine but on fish 256 the solarized color base03 (#002b36) displays as that dark grey color rather then the correct color that is displayed when i do have a `*-256color` term value. Perhaps I am barking up the wrong tree but I was under the impression that 256 color terms can display those hex values correctly yet that is not what i am seeing. My apologies if i am missing something.

**Comment by bpinto** [comment]
Could you run this command with and without 256 enabled?
```
echo (set_color -b green)(set_color 002b36) testing
```

I ran it here with my terminal configured with solarized dark theme and this is the output. The font color is gray, not white. Maybe I missed something?

![image](https://cloud.githubusercontent.com/assets/526122/6073947/9f64031e-ad9c-11e4-91a2-df3113bf7467.png)

**Comment by Nekroze** [comment]
That command output looks the same both with and without 256 color support. but the budspencer colors are still the same.

The problem I am trying to solve is that even though manually defined by hex color when using 256 color terminals I see the first picture I posted as the budspencer colours however the encircled colour in the below picture is no where defined nor in the solarized spec.
![fish-xterm](https://cloud.githubusercontent.com/assets/1460186/6074417/9e5280a0-ae09-11e4-8919-8e1837159c03.JPG)

Perhaps that makes more sense as to what I mean. If not let me know if you would like me to just desist and close this issue off.

**Comment by tannhuber** [comment]
Can you check the output of
https://github.com/hut/ranger/blob/master/doc/tools/print_colors.py in order to check whether your terminal is configured for 256 colors?

**Comment by Nekroze** [comment]
@tannhuber Indeed i do get the correct 256 output when i set the term to 256 and 8 when i set it to just "screen"

**Comment by tannhuber** [comment]
I think you should set it to 256 color support. Can you tell me the content of your color definitions as well?
```
echo $budspencer_colors
```
Then, I can check it on my own. Which terminal emulator do you use?

**Comment by Nekroze** [comment]
@tannhuber Here is the result of that command:

`839496 002b36 073642 586e75 b58900 cb4b16 dc322f d33682 6c71c4 268bd2 2aa198 859900`

I get this using putty and terminology (only ones i have tried) both with and without tmux.

**Comment by tannhuber** [comment]
I think, I get your point. You find the explanation [here][colors].
[colors]: https://github.com/fish-shell/fish-shell/issues/1464]

**Comment by Nekroze** [comment]
@tannhuber Interesting but shouldn't that $budspencer_colors override this and enforce the colors?

**Comment by tannhuber** [comment]
The theme uses the `set_color` command as well. I haven't found a possibility to set arbitrary colors by their hex values yet. If anybody knows how to manage it, please tell me. But due to the fact that terminal emulators are antiquated, I think it wouldn't be possible at all. There're some newer terminals using webkit in order to show images and proportional fonts within terminals. These terminals may be able to show all available colors as well. But they are still experimental and might behave strangely.

**Comment by bpinto** [comment]
I think we finally have a "solution" for this.
