### ISSUE TITLE
bobthefish theme question

### ISSUE THREAD

**Issue by pbowyer** [bpinto/oh-my-fish#370]
Great work on oh-my-fish - coming from ZSH I appreciate it, but even more so the differences!

I have been trying to get `bobthefish` theme to work as shown on http://bleibinha.us/blog/2014/08/my-command-line-setup-with-fish#bobthefish but I am stuck with a red chevron at the start of every single prompt.
![Screenshot](https://dl.dropboxusercontent.com/u/2460167/Screenshot%202015-02-10%2021.18.58.png)
 No matter where I am in the file system, it's present. If I switch to the `agnoster` theme this isn't present.

Is there an issue with my configuration? Thanks

**Comment by bobthecow** [comment]
That's your ruby version. Do you use RVM or rbenv?

**Comment by pbowyer** [comment]
Thanks, I don't have either installed. Here's some more Ruby information:
![](https://dl.dropboxusercontent.com/u/2460167/Screenshot%202015-02-10%2021.45.59.png)

**Comment by bobthecow** [comment]
how about `which rvm-prompt`?

**Comment by bobthecow** [comment]
I figured it out :)

**Comment by pbowyer** [comment]
Brilliant thank you! Will test & confirm tomorrow.

**Comment by turiphro** [comment]
Not sure this is the right place, but google brought me here and it seems closely related:

On Ubuntu 14.04 default installation (fish APT version) and master checkout, using bobthefish, I'm getting this error for *every* prompt:
`type: Could not find “rvm-prompt”`

It's not installed indeed but shouldn't return an error IMHO.

As a quick fix you can add this to your .config/fish/config.fish file:
set theme_display_ruby no

**Comment by bobthecow** [comment]
What's your fish version number?

**Comment by turiphro** [comment]
fish, version 2.1.2-1247-gfbe28fd

**Comment by bpinto** [comment]
Should `theme_display_ruby` usage be defaulted to no?

**Comment by bobthecow** [comment]
No, it should default to yes, but it shouldn't do anything if there's no reason to do anything. `type rvm-prompt >/dev/null` shouldn't output anything. bobthefish is just using its exit status. For some reason, it's leaking... mebbe in the version of fish @turiphro has the output is on stderr instead of stdout like it is for me?

**Comment by bobthecow** [comment]
@turiphro this is fixed in #433, pls update :)
