### ISSUE TITLE
Code naming conventions and style guide for OMF

### ISSUE THREAD

**Issue by bucaran** [bpinto/oh-my-fish#372]
The fish docs can't possibly cover all corners. A list of guidelines that we can all agree on would be really helpful and fun to discuss :)

**Comment by bpinto** [comment]
I'd prefer not to deviate from fish shell documentation, and submit PRs to fix their documentation in case there is something missing.

The only thing I strongly dislike is having 4 spaces for indentation so I decided to use 2 instead.

**Comment by bucaran** [comment]
fish uses [this](https://github.com/fish-shell/fish-shell/blob/master/CONTRIBUTING.md) as style guide for C++ contributions, but as far as fish goes, there is not a lot of advice from the fish elders.

In this style guide we could cover things like 
```fish
if block
end
# VS
block
  and ...
```

And many other common recurring patterns.

**Comment by bpinto** [comment]
We can try, yep.

That example would be an endless discussion between you and me? :P

https://github.com/fish-shell/fish-shell/issues/1838 brings tears to my eyes, tabs? :(

**Comment by bucaran** [comment]
I think the second case can be useful sometimes, like when you are certain there will be no other code if that condition is true / false, etc.

But the first case would be the recommended one for all other cases.

I prefer spaces too, but I don't have a good argument against tabs really. [This](http://programmers.stackexchange.com/questions/57/tabs-versus-spaces-what-is-the-proper-indentation-character-for-everything-in-e) is a good resource.

**Comment by bpinto** [comment]
Tabs/spaces vim/emacs. There is no right and wrong, just personal preference.

**Comment by bucaran** [comment]
In go you use tabs, and it's up to [gofmt](https://golang.org/cmd/gofmt/) to format/style your code.

That's why a style guide is useful. It's like the _law_. OMF uses 2 spaces instead of tabs. This is a good one.

**Comment by bucaran** [comment]
Closing this as it didn't get enough track. I may get around this later myself.
