### ISSUE TITLE
Oh-my-fish logo

### ISSUE THREAD

**Issue by bucaran** [bpinto/oh-my-fish#380]
Wants website...

Just thinking out loud.

**Comment by bpinto** [comment]
For sure I want that, but I would like us to have an awesome logo before that. :P

**Comment by bucaran** [comment]
:+1: I will give it a shot later today.

**Comment by bucaran** [comment]
I have two more plugins on the way BTW. Sorry :laughing:

**Comment by bpinto** [comment]
As long as you are not working on a `require` plugin. :P

**Comment by bucaran** [comment]
Hehe. Nope.

**Comment by bucaran** [comment]
Does anyone have any ideas for what the logo should look like?

**Comment by marcker** [comment]
+ :+1:

**Comment by bucaran** [comment]
@marcker I thumbs up? Just kidding. Now, seriously though, any ideas?

**Comment by Bfgeshka** [comment]
Maybe fish?

**Comment by marcker** [comment]
I'm not designer, but I can try to make a logo.

**Comment by bucaran** [comment]
@marcker If you are willing to give it a shot, yes, why not? Go for it and let us know when you have something. :smile:

**Comment by marcker** [comment]
I started to sketch some ideas for the logo. What do you think? Suggestions?
![oh-my-fish](https://cloud.githubusercontent.com/assets/958723/6732868/46ac715a-ce2d-11e4-881c-13aa13d9182d.jpg)

**Comment by bucaran** [comment]
I think it looks awesome.

**Comment by bucaran** [comment]
@marcker Are you finished?

**Comment by marcker** [comment]
I think I still deserve some more touch (or all) and maybe adaptations for icons (16, 32, ..., n pixels). Do you think that it was good ... Thanks for this.

![oh-my-fish-1](https://cloud.githubusercontent.com/assets/958723/6804482/ae27aa46-d21c-11e4-8a48-0cd1407c8789.png)

**Comment by bucaran** [comment]
I liked the original better with the gray gradient in the window buttons. Any reason why you didn't simply used the traditional red, yellow, green palette?

**Comment by marcker** [comment]
My first version was colored ;-)
I'll make the adjustments and post soon.

**Comment by marcker** [comment]
We have some icons...

![icons-preview](https://cloud.githubusercontent.com/assets/958723/6825248/e514fa84-d2d7-11e4-91ce-dcdc8c1d106d.png)

**Comment by bucaran** [comment]
Great work @marcker I think it's perfect. 

Can you paste the last version in its largest version and without the background?

Please, also [choose a license](http://creativecommons.org/choose/).

**Comment by marcker** [comment]
![icon-full](https://cloud.githubusercontent.com/assets/958723/6832231/ea6dcbd8-d303-11e4-97d8-e9b8a8922c22.png)

My license: http://creativecommons.org/licenses/by/4.0/

**Comment by bobthecow** [comment]
Nice!

What if you added a stroke to the right edge of the tail so it evokes a `>>>` prompt a bit more? Something like this awful hack job, but better ;)

![fish-riff](https://cloud.githubusercontent.com/assets/53660/6836770/b5e81f40-d302-11e4-99b5-8bf3a3abc987.png)

**Comment by bucaran** [comment]
:+1: For @bobthecow edits.

**Comment by marcker** [comment]
:+1: too

**Comment by bucaran** [comment]
Thanks, make sure that _if_ the tip of the `>` is round, the carved shape in the head of the fish is also round as well.

**Comment by bobthecow** [comment]
Again: do a good job of it, not the crappy job I did ;)

**Comment by marcker** [comment]
Something like that?

![fish-1](https://cloud.githubusercontent.com/assets/958723/6846973/77bf403c-d3a1-11e4-9ed8-e183feb148a8.png)

![fish-2](https://cloud.githubusercontent.com/assets/958723/6846975/77beb6f8-d3a1-11e4-81dc-13cc3460b193.png)

![fish-3](https://cloud.githubusercontent.com/assets/958723/6846974/77c2482c-d3a1-11e4-92fe-f072a6ac5403.png)

**Comment by bucaran** [comment]
Definitely the first.

**Comment by marcker** [comment]
The first with props:

![oh-my-fish-icon-128px-recuperado-new](https://cloud.githubusercontent.com/assets/958723/6847080/803ba902-d3a2-11e4-988c-82dd7d0b755b.png)

**Comment by bobthecow** [comment]
I think I like the symmetry of it with the tail the same height as the body.

**Comment by marcker** [comment]
Testing...

![fish-4](https://cloud.githubusercontent.com/assets/958723/6847746/8d1b95b0-d3a7-11e4-866a-6bdc1eea0fe6.png)

**Comment by bobthecow** [comment]
:+1: That's my favorite so far.

**Comment by syl20bnr** [comment]
last fish with the prompt is excellent :+1: 
I also like when it is enclosed in a terminal window.

**Comment by bucaran** [comment]
Last one with terminal window :+1: 

Do we have a winner?

**Comment by bobthecow** [comment]
:+1:

**Comment by bucaran** [comment]
You heard them @marcker and thanks again for the awesome work.

Why don't you prepare a PR updating the README.

Please add due credit to yourself :smile:

**Comment by marcker** [comment]
Ok, wip...

**Comment by bucaran** [comment]
This would also be the logo if _oh-my-fish_ is transferred to its own organization someday. #407

**Comment by marcker** [comment]
Final version:

![final](https://cloud.githubusercontent.com/assets/958723/6883431/9beb62b0-d58b-11e4-902c-2f716859a7ad.png)

**Comment by bobthecow** [comment]
:+1: Awesome. Thanks for your work on this :)

**Comment by bpinto** [comment]
Great logo! Thanks @marcker @bobthecow @bucaran

**Comment by bpinto** [comment]
@marcker Could you share a vectorized version? And also share the colors used, etc.?

**Comment by bucaran** [comment]
Colors are [here](https://cloud.githubusercontent.com/assets/958723/6825248/e514fa84-d2d7-11e4-91ce-dcdc8c1d106d.png).

**Comment by marcker** [comment]
@bpinto, here is the [logo in PSD](https://onedrive.live.com/redir?resid=A24FAFAB6ADBA68C!564&authkey=!AEK6oQgKND5jFzw&ithint=file%2cpsd)

Any questions report to me.

**Comment by bpinto** [comment]
Thanks again!
