### ISSUE TITLE
Improving pyenv plugin

### ISSUE THREAD

**Issue by bucaran** [bpinto/oh-my-fish#388]
@bpinto @exzz

Before submitting a patch, I thought I'd ask:

Instead of:

```fish
if test -n "$PYENV_ROOT"
  _prepend_path $PYENV_ROOT/bin
  _prepend_path $PYENV_ROOT/shims
else
  _prepend_path $HOME/.pyenv/bin
  _prepend_path $HOME/.pyenv/shims
end
```

What about:

```fish
if not test -q PYENV_ROOT
  set PYENV_ROOT $HOME/.pyenv
end

if test -n "$PYENV_ROOT"
  _prepend_path $PYENV_ROOT/bin
  _prepend_path $PYENV_ROOT/shims
end
```

Any other ideas about how to make `pyenv` plugin more useful are appreciated.

**Comment by bucaran** [comment]
#389

**Comment by bpinto** [comment]
I think this if statement is better.

**Comment by bucaran** [comment]
@bpinto The original one it's redundant. Shouldn't we be able to combine `pyenv` and `rbenv`, given than both are essentially the same?

**Comment by bucaran** [comment]
Please see #393
