### ISSUE TITLE
git plugin

### ISSUE THREAD

**Issue by despairblue** [bpinto/oh-my-fish#397]
Just wondering, the README.md mentions a git plugin, but the `plugins` folder does not contain one. What am I missing here? Is it defined elsewhere?

**Comment by bucaran** [comment]
This probably refers to the git-flow completions maybe? I can't check right now.

**Comment by despairblue** [comment]
It might, but then, the README.md should be updated to mention `set fish_plugins git-flow rails` instead of `set fish_plugins git rails`.

I was actually expecting something like @jcouyang https://github.com/bpinto/oh-my-fish/pull/277 proposal: easily activatable aliases (preferably the same ones OMZ uses, for easier migration).
They save a ton of time (`gco` -> `git checkout`, `gss` -> `git status --short`, `gp` -> `git push`, `gl` -> `git pull`, `gc` -> `git commit`).

**Comment by bucaran** [comment]
@despairblue You are completely right. To be clear, `git` could indeed be a plugin if someone created one with that name, but to be consistent it should be `git-flow`. Do you want to send a PR? :smile:

**Comment by despairblue** [comment]
will do when I'm home

**Comment by despairblue** [comment]
And just out of curiosity, why will be plugins that simply contain aliases not accepted? And shouldn't that be mentioned in a contribution guide or something?

**Comment by bobthecow** [comment]
Because aliases are incredibly personal, and because they're so short, the potential for conflict is very high. My perfect mnemonics might be awful for you — just try to guess what `pp`, `ppr` and `spp` mean ;) Things you think are a good idea to shorten, I might use infrequently enough to just use tab completion instead.

**Comment by bucaran** [comment]
Add a custom plugin with your own aliases to `$HOME/$fish_path/custom/`. :smile:

**Comment by despairblue** [comment]
@bobthecow I know where you coming from, that's why I wouldn't suggest things like my `gitassume`, `gitassume-no` or `gitassume-show` aliases (which are probably still easy to guess, but `git update-index --assume-unchanged` is not widely used so they wouldn't be a sane default :smile:), but I'd definitely argue that `git pull, push, commit, log, status` are always used a lot.

It would be cool to have a sane default set of aliases, even separate from a possible git package that could provide different functionality (no idea what), like in a git-aliases package. Right now when I'm at a coworkers or friends computer and they use the OMZ git plugin I know their aliases, that saves a lot of typing. Sure there will always be things that are so specific that it would be darn stupid to add it here, and there will be stuff that might be disputable, but on the other end of the spectrum there might also be things that simply are no-brainers, like `gc` for `git commit`.

Also looking plugins like `python`, they look even more opinionated than simple aliases, I mean, having a general purpose file server in the `python` plugin, really?

And even after quite some thinking, I couldn't come up with what kind of git aliases `pp`, `ppr` and `spp` could be. I actually think there aren't any git aliases :wink:. Guessing without context is kinda hard, if I tell someone that `gc` is a git alias they probably know what it is, especially if they're coming from OMZ.

I'd argue that some aliases should be a little like CLI tools in general. Someone decided how to call a tool and it's parameters, so someone should also decide on some default aliases. It would make working on others computers much easier, as well as communication while helping someone to solve a problem remotely.

Another alternative would be to allow pulling other git repos into `$HOME/$fish_path/custom/` and keeping them up to date with OMF. Does OMF has an auto update? Then one could create a wiki page with a list of external plugins (they would have to open PR to be added or updated). That would keep the core clean and unopinionated.

**Comment by bucaran** [comment]
@despairblue Like a dotfiles sharing plugin for OMF? Sounds interesting. I already have a basic sync solution for my own [dotfiles](), but it's using `bash`. Mmmm.

I totally agree about the `python` plugin. These were created very early when @bpinto first kicked off the framework, so I guess at the time something was better than nothing and it seemed OK.

I keep my git aliases in my gitconfig and sync it up with my dotfiles.

**Comment by despairblue** [comment]
Ok, I'll think something up over the weekend. 

Your dotfiles script looks pretty extensive, like an auto configuration solution. I actually went the [boxen](https://github.com/boxen/our-boxen/) route for this created something [similar albeit simpler](https://github.com/despairblue/puppet/tree/master/modules). For simple config file sharing I use a dropbox folder and a small bash script that's using [stow](https://www.gnu.org/software/stow/) for this:
```bash
#!/bin/bash -ex
# Usage: `./homestow {config}`

STOWDIR=~/Dropbox/dotfiles
TARGETDIR=~

# echo $*

stow -v -d $STOWDIR -t $TARGETDIR "$@"
```

`homestow atom` symlinks my atom configs to my `~/.atom` then.

Especially things that are automatically changed by programs (like my atom config) are usually easier handled in dropbox, whereas things like disabling the boot sound fit better into a puppet manifest. But this is getting off topic ^^

I hope I have some time this weekend to think about some plugin sharing mechanism.

**Comment by bucaran** [comment]
Things are still a bit disorganized. The gitfiles and fish config is actually [here](https://github.com/bucaran/dotfiles).

Never heard of _stow_ before. I will take a look at it and steal me something :+1:  

Thanks!

**Comment by bucaran** [comment]
Closing this.

**Comment by despairblue** [comment]
Merging [this](https://github.com/bpinto/oh-my-fish/pull/399) would actually solve the initial problem, the ambiguity in the README.md.

**Comment by bucaran** [comment]
You are right and I missed that PR. Try adding a title along with the `closing #<issue number>` text next time.

Thanks.
