### ISSUE TITLE
Theme only partially changing?

### ISSUE THREAD

**Issue by sgunturi** [bpinto/oh-my-fish#400]
When I try to change my theme using `theme` it looks like it's only partially taking effect - see screenshot:

![screenshot 2015-03-05 22 59 29](https://cloud.githubusercontent.com/assets/3508056/6520449/551e0a48-c38b-11e4-90d0-89c2ad998eb9.png)

I'm new to fish, so I need a little help debugging.

**Comment by sgunturi** [comment]
Title of the issue may be a little misleading - before, the timestamps were toggling depending on the theme, but now it looks like they're here to stay.

**Comment by bobthecow** [comment]
@sgunturi I bet `theme` isn't resetting the right prompt. Did they appear when you tried bobthefish?

**Comment by sgunturi** [comment]
Yes - setting `theme bobthefish` is still giving me timestamps.

Is there a variable I can echo to see what the theme is set to?

**Comment by bobthecow** [comment]
I don't know much about the themes plugin. If you set it to something besides `bobthefish` and open a new tab, does the right prompt still show up?

**Comment by sgunturi** [comment]
No - the same theme.

For what it's worth, I was able to get the theme to change using the editor from `fish_config`. Could it be setting something way upstream that `theme` can't override?

**Comment by sgunturi** [comment]
Also - changing the theme in my `.config/fish/config.fish` file to `bobthefish` gave me this output:
![screenshot 2015-03-05 23 19 56](https://cloud.githubusercontent.com/assets/3508056/6520579/27ad2e2e-c38e-11e4-9695-60dab05fd7b3.png)

which is more inline with what I was seeing when I created the title for the issue - parts of the prompt are changing, others are not.

**Comment by bobthecow** [comment]
The right prompt issue (the timestamp) seems to be that if you switch to a theme which uses a right prompt, then switch back to one that doesn't, the right prompt from the previous theme sticks around. So, for example, if you try `edan`, your right prompt should change to a `~` or something. If you switch to `agnoster` after that, it'll stay a tilde because agnoster doesn't supply a right prompt. If you then switch to `bobthefish`, it'll go back to a timestamp.

**Comment by bobthecow** [comment]
Can you paste the contents of your config.fish? That's not bobthefish at all.

**Comment by bobthecow** [comment]
Well, it is the greeting from bobthefish. But it's not the prompt.

**Comment by sgunturi** [comment]
Right - looking at the theme files, my guess is the greeting is working fine but the prompt and the right are not.

Here's my config.fish.

```
# Path to your oh-my-fish.
set fish_path $HOME/.oh-my-fish

# Theme
set fish_theme bobthefish

# All built-in plugins can be found at ~/.oh-my-fish/plugins/
# Custom plugins may be added to ~/.oh-my-fish/custom/plugins/
# Enable plugins by adding their name separated by a space to the line below.
set fish_plugins theme z tab localhost

# Path to your custom folder (default path is ~/.oh-my-fish/custom)
#set fish_custom $HOME/dotfiles/oh-my-fish

# Load oh-my-fish configuration.
. $fish_path/oh-my-fish.fish
```

**Comment by bobthecow** [comment]
Do you have anything else in your `~/.config/fish` folder?

**Comment by bobthecow** [comment]
Or your $fish_custom, I guess.

**Comment by bobthecow** [comment]
If you define a `fish_prompt` function in `~/.oh-my-fish/custom`, it will likely override (or at least fight with) whatever the theme provides. This could be the cause of some of your weirdness with the `theme` plugin, as well, since that plugin does a lot of funky things with the function path.

**Comment by sgunturi** [comment]
Your guess was right on - 
![screenshot 2015-03-05 23 24 48](https://cloud.githubusercontent.com/assets/3508056/6520625/d58a5724-c38e-11e4-908f-ce75f7817e33.png)

I do have something else in my `.config/fish` folder - a folder called `functions`, which has a file called `fish_prompt.zsh`. Looks like this file is what the `fish_config` command uses to set the prompt. Axing this folder fixed it!

![screenshot 2015-03-05 23 28 36](https://cloud.githubusercontent.com/assets/3508056/6520664/5f2c6724-c38f-11e4-8975-55f192094896.png)

Do you think there needs to be documentation mentioning that `theme` and `fish_config` are incompatible with each other? Or is that something that is pretty well known?

Can help with a PR if it's warranted.

**Comment by bobthecow** [comment]
Basically, fish has a whole set of folders that it automatically loads functions from. It looks for files with the same name as the function it's trying to run. What order it searches them determines which "wins". So oh-my-fish (and the theme plugin) add the theme folder you want to the functions paths that are searched, but — if I were to guess — they don't want the theme-defined version to be the highest priority. If they let your custom-defined function win over the theme default, you could pick a theme like `bobthefish` but override the right prompt to do something different, for example.

**Comment by bucaran** [comment]
@bobthecow Thanks!

@sgunturi It might be worth mentioning. How could we phrase that?

**Comment by sgunturi** [comment]
@bucaran - I think a 1-2 liner in the theme plugin README might work-

Something like- 

Note: the `fish_config` web UI that comes bundled with the `fish` installation breaks how `theme` switches themes. If you've already used `fish_config`, deleting `~/.config/fish/functions/fish_prompt.fish` will make `theme` work again.

How does that sound?

**Comment by NathanJang** [comment]
Yes, please. I wasted some time looking for what was wrong. In my case, the theme wasn't changing at all.
