### ISSUE TITLE
vi-mode plugin inserts control characters when the shell is run in non-interactive mode

### ISSUE THREAD

**Issue by RomanHargrave** [bpinto/oh-my-fish#406]
VI-Mode will inject terminal control codes into stdout, even when the shell is run non-interactively (e.g. as a subshell, or called from a program using system()). I discovered this when debugging a strange issue I was having with the neovim clipboard.

Here's a shell script that demos the issue

```fish
# Assume that vi-mode is in $fish_plugins
fish -c 'echo test' | xxd
# 0000000: 1b5b 3330 6d1b 2842 1b5b 6d74 6573 740a  .[30m.(B.[mtest.

# Now, assume that vi-mode is not in $fish_plugins
fish -c 'echo test' | xxd
# 0000000: 7465 7374 0a                             test.
```

This causes some pretty major pain for applications that rely on subshell output.

As a temporary fix, you may conditionally load vi-mode

```fish
# ...
if isatty
    set fish_plugins $fish_plugins vi-mode
end
# ...
```

**Comment by bucaran** [comment]
I don't use the `vi` plugin, so I can't really comment here. Have you thought of an another fix for the issue?

Thanks for reporting this.

**Comment by RomanHargrave** [comment]
@bucaran one possible fix is to put the conditional wrapper inside vi-mode.fish

**Comment by bucaran** [comment]
You are welcome to submit a PR with a fix.
