### ISSUE TITLE
Does oh-my-fish belong to an organization?

### ISSUE THREAD

**Issue by bucaran** [bpinto/oh-my-fish#407]
#259.

If there's ever an _oh-my-fish.com_ website, I could see the benefit of moving OMF into its own organization, but I don't know if there's any other real benefit.

**Comment by bucaran** [comment]
@bpinto Thoughts?

**Comment by bpinto** [comment]
I believe https://github.com/bpinto/oh-my-fish/pull/381 needs to be completed before we can become an organization, in order to better handle the git remote change.

**Comment by bucaran** [comment]
:+1:
