### ISSUE TITLE
Fox theme throwing math.fish error after changing into git repo

### ISSUE THREAD

**Issue by musophob** [bpinto/oh-my-fish#413]
Here's my fish.conf:

    # hide the greeting
    set fish_greeting ""
    
    # Path to your oh-my-fish.
    set fish_path $HOME/.config/oh-my-fish
    
    # Theme
    set fish_theme agnoster
    
    # All built-in plugins can be found at ~/.oh-my-fish/plugins/
    # Custom plugins may be added to ~/.oh-my-fish/custom/plugins/
    # Enable plugins by adding their name separated by a space to the line below.
    set fish_plugins theme
    
    # Path to your custom folder (default path is ~/.oh-my-fish/custom)
    #set fish_custom $HOME/dotfiles/oh-my-fish
    
    # Load oh-my-fish configuration.
    . $fish_path/oh-my-fish.fish
    
    # load custom functions
    
    for file in $HOME/.config/fish/functions/*.fish
      . $file
    end

When I change into a directory with git, I get the following output:

    ┌[me@computer]-(~)
    └> cd www/mygitproject/
    switch: Expected exactly one argument, got 27
    /usr/local/Cellar/fish/2.1.2/share/fish/functions/math.fish (line 12):      switch $out
                                                                                           ^
    in function 'math',
        called on line 472 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',
        with parameter list '0 - 0'

    in command substitution
        called on line 476 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in function '__fish_git_prompt_informative_status',
        called on line 334 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in command substitution
        called on line 362 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in function '__fish_git_prompt',
        called on line 37 of file '/Users/sean/.config/oh-my-fish/themes/fox/fish_prompt.fish',
        with parameter list '-[git://%s]-'

    in function 'fish_prompt',
        called on standard input,

    in command substitution
        called on standard input,

           switch − switch ‐ conditionally execute a block of commands

    switch ‐ conditionally execute a block of commands
       Synopsis
           switch VALUE; [case [WILDCARD...]; [COMMANDS...]; ...] end

    switch: Type 'help switch' for related documentation

    switch: Expected exactly one argument, got 27
    /usr/local/Cellar/fish/2.1.2/share/fish/functions/math.fish (line 12):      switch $out
                                                                                           ^
    in function 'math',
        called on line 472 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',
        with parameter list '0 - 0'

    in command substitution
        called on line 478 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in function '__fish_git_prompt_informative_status',
        called on line 334 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in command substitution
        called on line 362 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in function '__fish_git_prompt',
        called on line 37 of file '/Users/sean/.config/oh-my-fish/themes/fox/fish_prompt.fish',
        with parameter list '-[git://%s]-'

    in function 'fish_prompt',
        called on standard input,

    in command substitution
        called on standard input,

           switch − switch ‐ conditionally execute a block of commands

    switch ‐ conditionally execute a block of commands
       Synopsis
           switch VALUE; [case [WILDCARD...]; [COMMANDS...]; ...] end

    switch: Type 'help switch' for related documentation

    switch: Expected exactly one argument, got 27
    /usr/local/Cellar/fish/2.1.2/share/fish/functions/math.fish (line 12):      switch $out
                                                                                           ^
    in function 'math',
        called on line 472 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',
        with parameter list 'brew-cask provides a friendly homebrew-style CLI workflow for the administration of Mac applications distributed as binaries.  !!  !! no command verb:  !!   Commands:      alfred     displays note about new built-in alfred support     audit      verifies installability of Casks     cat        dump raw source of the given Cask to the standard output     cleanup    cleans up cached downloads and tracker symlinks     create     creates the given Cask and opens it in an editor     doctor     checks for configuration issues     edit       edits the given Cask     fetch      downloads Cask resources to local cache     home       opens the homepage of the given Cask     info       displays information about the given Cask     install    installs the given Cask     list       with no args, lists installed Casks; given installed Casks, lists staged files     search     searches all known Casks     uninstall  uninstalls the given Cask     update     a synonym for 'brew update'     zap        zaps all files associated with the given Cask  See also "man brew-cask" + 0 + brew-cask provides a friendly homebrew-style CLI workflow for the administration of Mac applications distributed as binaries.  !!  !! no command verb:  !!   Commands:      alfred     displays note about new built-in alfred support     audit      verifies installability of Casks     cat        dump raw source of the given Cask to the standard output     cleanup    cleans up cached downloads and tracker symlinks     create     creates the given Cask and opens it in an editor     doctor     checks for configuration issues     edit       edits the given Cask     fetch      downloads Cask resources to local cache     home       opens the homepage of the given Cask     info       displays information about the given Cask     install    installs the given Cask     list       with no args, lists installed Casks; given installed Casks, lists staged files     search     searches all known Casks     uninstall  uninstalls the given Cask     update     a synonym for 'brew update'     zap        zaps all files associated with the given Cask  See also "man brew-cask" + 0'

    in command substitution
        called on line 483 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in function '__fish_git_prompt_informative_status',
        called on line 334 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in command substitution
        called on line 362 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in function '__fish_git_prompt',
        called on line 37 of file '/Users/sean/.config/oh-my-fish/themes/fox/fish_prompt.fish',
        with parameter list '-[git://%s]-'

    in function 'fish_prompt',
        called on standard input,

    in command substitution
        called on standard input,

           switch − switch ‐ conditionally execute a block of commands

    switch ‐ conditionally execute a block of commands
       Synopsis
           switch VALUE; [case [WILDCARD...]; [COMMANDS...]; ...] end

    switch: Type 'help switch' for related documentation

    > switch: Expected exactly one argument, got 27
    /usr/local/Cellar/fish/2.1.2/share/fish/functions/math.fish (line 12):      switch $out
                                                                                           ^
    in function 'math',
        called on line 472 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',
        with parameter list '0 - 0'

    in command substitution
        called on line 476 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in function '__fish_git_prompt_informative_status',
        called on line 334 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in command substitution
        called on line 362 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in function '__fish_git_prompt',
        called on line 37 of file '/Users/sean/.config/oh-my-fish/themes/fox/fish_prompt.fish',
        with parameter list '-[git://%s]-'

    in function 'fish_prompt',
        called on standard input,

    in command substitution
        called on standard input,

           switch − switch ‐ conditionally execute a block of commands

    switch ‐ conditionally execute a block of commands
       Synopsis
           switch VALUE; [case [WILDCARD...]; [COMMANDS...]; ...] end

    switch: Type 'help switch' for related documentation

    switch: Expected exactly one argument, got 27
    /usr/local/Cellar/fish/2.1.2/share/fish/functions/math.fish (line 12):      switch $out
                                                                                           ^
    in function 'math',
        called on line 472 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',
        with parameter list '0 - 0'

    in command substitution
        called on line 478 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in function '__fish_git_prompt_informative_status',
        called on line 334 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in command substitution
        called on line 362 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in function '__fish_git_prompt',
        called on line 37 of file '/Users/sean/.config/oh-my-fish/themes/fox/fish_prompt.fish',
        with parameter list '-[git://%s]-'

    in function 'fish_prompt',
        called on standard input,

    in command substitution
        called on standard input,

           switch − switch ‐ conditionally execute a block of commands

    switch ‐ conditionally execute a block of commands
       Synopsis
           switch VALUE; [case [WILDCARD...]; [COMMANDS...]; ...] end

    switch: Type 'help switch' for related documentation

    switch: Expected exactly one argument, got 27
    /usr/local/Cellar/fish/2.1.2/share/fish/functions/math.fish (line 12):      switch $out
                                                                                           ^
    in function 'math',
        called on line 472 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',
        with parameter list 'brew-cask provides a friendly homebrew-style CLI workflow for the administration of Mac applications distributed as binaries.  !!  !! no command verb:  !!   Commands:      alfred     displays note about new built-in alfred support     audit      verifies installability of Casks     cat        dump raw source of the given Cask to the standard output     cleanup    cleans up cached downloads and tracker symlinks     create     creates the given Cask and opens it in an editor     doctor     checks for configuration issues     edit       edits the given Cask     fetch      downloads Cask resources to local cache     home       opens the homepage of the given Cask     info       displays information about the given Cask     install    installs the given Cask     list       with no args, lists installed Casks; given installed Casks, lists staged files     search     searches all known Casks     uninstall  uninstalls the given Cask     update     a synonym for 'brew update'     zap        zaps all files associated with the given Cask  See also "man brew-cask" + 0 + brew-cask provides a friendly homebrew-style CLI workflow for the administration of Mac applications distributed as binaries.  !!  !! no command verb:  !!   Commands:      alfred     displays note about new built-in alfred support     audit      verifies installability of Casks     cat        dump raw source of the given Cask to the standard output     cleanup    cleans up cached downloads and tracker symlinks     create     creates the given Cask and opens it in an editor     doctor     checks for configuration issues     edit       edits the given Cask     fetch      downloads Cask resources to local cache     home       opens the homepage of the given Cask     info       displays information about the given Cask     install    installs the given Cask     list       with no args, lists installed Casks; given installed Casks, lists staged files     search     searches all known Casks     uninstall  uninstalls the given Cask     update     a synonym for 'brew update'     zap        zaps all files associated with the given Cask  See also "man brew-cask" + 0'

    in command substitution
        called on line 483 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in function '__fish_git_prompt_informative_status',
        called on line 334 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in command substitution
        called on line 362 of file '/usr/local/Cellar/fish/2.1.2/share/fish/functions/__fish_git_prompt.fish',

    in function '__fish_git_prompt',
        called on line 37 of file '/Users/sean/.config/oh-my-fish/themes/fox/fish_prompt.fish',
        with parameter list '-[git://%s]-'

    in function 'fish_prompt',
        called on standard input,

    in command substitution
        called on standard input,

           switch − switch ‐ conditionally execute a block of commands

    switch ‐ conditionally execute a block of commands
       Synopsis
           switch VALUE; [case [WILDCARD...]; [COMMANDS...]; ...] end

    switch: Type 'help switch' for related documentation

Commenting out git functions in the fox theme fixes this issue. Other themes from this repo work fine with git, such as agnoster.

**Comment by bucaran** [comment]
Does it only throw an error when using fox theme?

**Comment by bucaran** [comment]
> Notes

```fish
# load custom functions

for file in $HOME/.config/fish/functions/*.fish
  . $file
end
```

Why? _oh my fish_ already does this for you.

**Comment by musophob** [comment]
Thanks for the quick reply.

Turns out the culprit was:

    alias bc='brew cask'

O.o

With the above function disabled it works.

>> Re: note # 1

Re-read the readme, now I see the light - `.load` files in the `custom` directory. 

Much appreciated Jorge
