### ISSUE TITLE
Unknown command '_prepend_path' when using fish from fish-shell/master

### ISSUE THREAD

**Issue by nesl247** [bpinto/oh-my-fish#420]
Every few days I rebuild fish from fish-shell/master using `brew reinstall --HEAD fish`. After rebuilding it today, fish is now returning this on a fresh install of oh-my-fish.

```
fish: Unknown command '_prepend_tree'
fish:     _prepend_tree $fish_custom/$library   $skip_spec
          ^
in function 'import'
	called on line 24 of file ~/.oh-my-fish/oh-my-fish.fish
	with parameter list 'plugins/theme themes/robbyrussell'

from sourcing file ~/.oh-my-fish/oh-my-fish.fish
	called on line 155 of file /usr/local/Cellar/fish/HEAD/share/fish/config.fish

in function '.'
	called on line 16 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

fish: Unknown command '_prepend_path'
fish:     _prepend_path $fish_path/$library/completions -d fish_complete_path
          ^
in function 'import'
	called on line 24 of file ~/.oh-my-fish/oh-my-fish.fish
	with parameter list 'plugins/theme themes/robbyrussell'

from sourcing file ~/.oh-my-fish/oh-my-fish.fish
	called on line 155 of file /usr/local/Cellar/fish/HEAD/share/fish/config.fish

in function '.'
	called on line 16 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

fish: Unknown command '_prepend_tree'
fish:     _prepend_tree $fish_path/$library     $skip_spec
          ^
in function 'import'
	called on line 24 of file ~/.oh-my-fish/oh-my-fish.fish
	with parameter list 'plugins/theme themes/robbyrussell'

from sourcing file ~/.oh-my-fish/oh-my-fish.fish
	called on line 155 of file /usr/local/Cellar/fish/HEAD/share/fish/config.fish

in function '.'
	called on line 16 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

fish: Unknown command '_prepend_tree'
fish:     _prepend_tree $fish_custom/$library   $skip_spec
          ^
in function 'import'
	called on line 24 of file ~/.oh-my-fish/oh-my-fish.fish
	with parameter list 'plugins/theme themes/robbyrussell'

from sourcing file ~/.oh-my-fish/oh-my-fish.fish
	called on line 155 of file /usr/local/Cellar/fish/HEAD/share/fish/config.fish

in function '.'
	called on line 16 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup

fish: Unknown command '_prepend_path'
fish:     _prepend_path $fish_path/$library/completions -d fish_complete_path
          ^
in function 'import'
	called on line 24 of file ~/.oh-my-fish/oh-my-fish.fish
	with parameter list 'plugins/theme themes/robbyrussell'

from sourcing file ~/.oh-my-fish/oh-my-fish.fish
	called on line 155 of file /usr/local/Cellar/fish/HEAD/share/fish/config.fish

in function '.'
	called on line 16 of file ~/.config/fish/config.fish

from sourcing file ~/.config/fish/config.fish
	called during startup
```

**Comment by bucaran** [comment]
These functions exist inside `$fish_path/functions` so there must be something bad in your configuration.

What is the value of `$fish_path` on your system?

**Comment by nesl247** [comment]
This is on a fresh install, aka I wiped my ~/.oh-my-fish and ~/.config/fish.

**Comment by bucaran** [comment]
Obviously fish can't find `_prepend_tree` and friends. What is the value of `$fish_path` on your system?

**Comment by RomanHargrave** [comment]
Having this issue too, happened right after I built the latest fish. 

No longer getting errors, but *lots* of unexpected behavior from OMF, such as starting random garbage.

**Comment by bucaran** [comment]
Thanks for reporting this. I will update fish and reinstall OMF to see what broke as soon as I get a chance.

**Comment by RomanHargrave** [comment]
@bucaran Got the errors back (good thing). It looks like one of the changes made between `fish-shell#e421c12` and `fish-shell#8742867` is causing fish to skip the loading of functions starting with `_` in fish_functions_path. This likely boils down to fish-shell needing to correct the state of a single argument. The `_` bit is a feature called hidden functions that was last modified around 2012, as I am sure you are aware.

**Comment by RomanHargrave** [comment]
@bucaran @nesl247 a PR [just got merged](https://github.com/fish-shell/fish-shell/commit/fbe28fd5d8274c298c825428d89fbe20f4ae111e) that should fix the problem.

**Comment by nesl247** [comment]
Yep, the issue is fixed in the Pr that @RomanHargrave linked to.

**Comment by bucaran** [comment]
I was just able to reproduce the error, but I am glad this was sorted out.

This is the same thing that was causing #421to fail, but now it's passing, so now that everything is gone back to normal I want to thank @RomanHargrave and @nesl247 for keeping me posted about it.

:+1:
