### ISSUE TITLE
How to change color of directory

### ISSUE THREAD

**Issue by legatoo** [bpinto/oh-my-fish#426]
In my black ground terminal, the directory is in dark_blue which is not easy to see. I want to change the color of it but couldn't find where should I change? Does anyone can help?

**Comment by bucaran** [comment]
If you are a Mac user:

You can try creating your own `.terminal` theme, modifying the values of the default colors (see if [this](http://fishshell.com/docs/current/index.html#variables-color) helps) or if you want a quick solution just `CMD ,` and change it using terminal `Settings` (I am pretty sure iTerm2 have a similar way to accomplish this.)

![screen shot 2015-04-16 at 7 24 56 pm](https://cloud.githubusercontent.com/assets/8317250/7179012/a1c04268-e46e-11e4-9b2f-7e6afed02808.png)

**Comment by legatoo** [comment]
Thank you, now I know where to configure this.

**Comment by bobthecow** [comment]
@bucaran is right. You've likely got a poor default color scheme in your terminal. Either mess with your terminal app's settings, or check out something like [Solarized](http://ethanschoonover.com/solarized) or [base16](http://chriskempson.github.io/base16/), both of which have better contrast across the board.

**Comment by bpinto** [comment]
Both color themes are really good @bobthecow !

**Comment by erow80** [comment]
I'm confused as well. I thought that by configuring or setting a new theme, it would look exactly as the theme's screenshot. I've obviously not got something set correctly:

![screen shot 2015-05-08 at 4 31 08 pm](https://cloud.githubusercontent.com/assets/1077169/7547320/af6f5aba-f59f-11e4-8c45-91e13f2c579c.png)

![screen shot 2015-05-08 at 4 32 12 pm](https://cloud.githubusercontent.com/assets/1077169/7547325/cbe8c226-f59f-11e4-8ea0-c9d8b17f515d.png)

**Comment by bucaran** [comment]
@erow80 You'd think so, but nope. I think you already figured it out, but just for the record.

A _theme_, in the context of this conversation, does not modify colors, but rather uses colors from the palette of available colors. As anyone can see in the second screenshot above, the colors are naturally mapped as you would expected, but you can change the hues and tones of those reds, greens and blues as you wish. You don't even have to have blue for blue, you can change red for pink and yellow for orange, etc.

**Comment by erow80** [comment]
Okay thanks @bucaran. Could you explain the error that I received and why many of the custom styles attributed to each theme don't seem to be properly loading (as per my first screenshot)?

**Comment by bucaran** [comment]
@erow80 I wrote `theme`, but looking at the error, it seems more likely `budspencer` to be the one who is causing trouble.

You'll have to ask @tannhuber.

**Comment by tannhuber** [comment]
Of course, I'd like to help. Unfortunately I can't reproduce the error.
![scrot-2015-05-09-103456](https://cloud.githubusercontent.com/assets/2333069/7549488/171b83f4-f637-11e4-8071-44042e58fea4.png)

@erow80 Which fish version do you use?
