### ISSUE TITLE
grc plugin

### ISSUE THREAD

**Issue by tannhuber** [bpinto/oh-my-fish#431]
I think it's worth to nick the grc plugin from https://github.com/justinmayer/tackle/tree/master/plugins. Isn't it?

**Comment by bpinto** [comment]
I have never used grc, but probably worth.

It seems like this plugin could use a similar structure to the one we have for [bundler](https://github.com/bpinto/oh-my-fish/blob/master/plugins/bundler/bundler.load).

**Comment by bucaran** [comment]
@tannhuber It would be more useful to provide any relevant links included in the issue. I clicked the link above, but didn't make sense. 

What is grc?

**Comment by tannhuber** [comment]
@bucaran See here: http://www.grc.de/. :-)

http://kassiopeia.juls.savba.sk/~garabik/software/grc.html

**Comment by bucaran** [comment]
I used to own a GR, but never knew about the club :P

**Comment by tannhuber** [comment]
I opened a PR: https://github.com/bpinto/oh-my-fish/pull/435
I think I can close this issue.

@bucaran: Nice animals.

**Comment by bucaran** [comment]
Lovely indeed :smile:
