### ISSUE TITLE
Undistract

### ISSUE THREAD

**Issue by cazgp** [bpinto/oh-my-fish#432]
I've written a gist which notifies on long-running commands (uses tmux for one command atm, but hopefully that can change). It would be nice if that could get added to this repo if there isn't something already. Would it be a plugin? A utility as described in #430? Let me know if this is worth putting in and I can make a PR.

https://gist.github.com/cazgp/edf0e0d0ce6ec7f09821

**Comment by bucaran** [comment]
Sure! Can you make a plugin?

**Comment by bucaran** [comment]
Closing until @cazgp is back.

**Comment by cazgp** [comment]
Hey I could make a plugin, but it's still dependent upon tmux. I was hoping someone might be able to look at where tmux is used and suggest an alternative that's pure fish.

**Comment by bucaran** [comment]
I don't really use tmux enough so I can't comment on that part, but AFIK there is _pure fish_ way to do anything with tmux. You are still welcome to turn that into a plugin and submit it :smile:
