### ISSUE TITLE
bobthefish: git ls-files taking forever

### ISSUE THREAD

**Issue by larseggert** [bpinto/oh-my-fish#434]
The `git ls-files` command in `__bobthefish_prompt_git` is taking forever (minutes) on large NFS mounts.

Adding `--directory` removes that delay, but I'm unsure if functionality is affected.

**Comment by bobthecow** [comment]
Yeah, `--directory` doesn't do what we want :)

Your best bet is disabling it entirely, either for that repo or for your whole system. See #436 for a fix allowing that.
