### ISSUE TITLE
Plugin manager

### ISSUE THREAD

**Issue by Maxim-Filimonov** [bpinto/oh-my-fish#438]
I was wondering is there a plan to for a plugin manager for this project ? For example, i'd image something like Vundle configuration where I can list all the plugins I want to use with fish. Then you don't need to include the plugins themselves with oh-my-fish instead it's just default plugin set for plugin manager.
Something like https://github.com/zsh-users/antigen

Oh-my-zsh community already faced [issues](https://joshldavis.com/2014/07/26/oh-my-zsh-is-a-disease-antigen-is-the-vaccine/) with trying to include everything into one giant repo, maybe we can learn from them

**Comment by bucaran** [comment]
:+1: See #431 #259 #271

Thanks for the link to the `oh-my-zsh` article.

**Comment by Maxim-Filimonov** [comment]
Lol i'm blind :trollface: One of the issue even have the same exact name :\ Sorry for that i'll chime in on existing issues
