### ISSUE TITLE
Installation overwrote my config.fish

### ISSUE THREAD

**Issue by josiahsprague** [bpinto/oh-my-fish#439]
I had a config.fish file with a custom PATH among other things, and when I installed oh-my-fish, that was completely overwriten! :(

**Comment by bucaran** [comment]
That's odd, here is what happens when you install `omf`:

```fish
# Check any existing config.fish files, backup and add custom template.
log blue "Looking for an existing fish config..."
if test -f $config_path/config.fish
  log green "Found $config_path/config.fish."
  log green "Backing up to $config_path/config.orig"
  mv $config_path/config.{fish,orig}
end
log blue "Adding default configuration file to $config_path/config.fish"
cp $fish_path/templates/config.fish $config_path/config.fish
```
You should have your _original_ config renamed to `config.orig`. Please check again and let me know.

**Comment by josiahsprague** [comment]
Yeah, I did find that `config.orig`, but I hadn't seen any indication or warning that my `config.fish` would be moved there. I was able to recover my customizations and add `omf` config manually. But I'm curious why the install is so destructive? Why not create the backup, and then just add `omf` related things to `config.fish` without wiping it?

**Comment by bucaran** [comment]
You are right, the current scheme could be improved like you say. I think this is a good idea.

**Comment by bobthecow** [comment]
It should let you know, during installation, but combining your current config with the generated config is just wrong. There are more ways for that to go wrong than we can even imagine :)

**Comment by josiahsprague** [comment]
I'm not saying nothing could go wrong, but what are some examples? I'd rather run that risk, with a backup, than having all of my customizations wiped out.

**Comment by bobthecow** [comment]
but your customizations aren't wiped out. they're saved. you just need to do the merge yourself.

**Comment by bucaran** [comment]
@josiahsprague Your customizations are saved to `config.orig`. Nothing is _"wiped out"_.

> It should let you know, during installation

It lets you know, kind of:

```fish
log green "Found $config_path/config.fish."
log green "Backing up to $config_path/config.orig"
```

**Comment by bpinto** [comment]
I'm with @bobthecow here. We occasionally have issues raised because of wrong user configuration, auto merging would likely increase these issues.

We already log on the console that the file has been saved with a different name. Perhaps we need to be clearer?

Only problem is that people usually don't read install logs. I'm included :p

**Comment by josiahsprague** [comment]
Maybe a note in the "Installation" section of the readme? I didn't closely read the console log during the install when the install completed successfully. I just restarted fish, which made all of those logs disappear.

**Comment by bucaran** [comment]
@josiahsprague Sounds more like it. Do you want to add it? :smile:
