### ISSUE TITLE
Prevent clobbering `config.orig`

### ISSUE THREAD

**Issue by bobthecow** [bpinto/oh-my-fish#443]
Should we check for `config.orig` before moving `config.fish` over the top of it?

**Comment by bpinto** [comment]
Infinite backup?

**Comment by bobthecow** [comment]
Nah, just refuse to install ;)

**Comment by bucaran** [comment]
Or just create a `<prefix>.config.orig`, where prefix can be a keyword or a random sequence of characters.

**Comment by bpinto** [comment]
I honestly don't think this is necessary.

1. One backup should be enough.
2. I expect all fish users to have their dotfiles stored somewhere else.

**Comment by bucaran** [comment]
> I expect all fish users to have their dotfiles stored somewhere else.

Yup

**Comment by bobthecow** [comment]
Right. Which is why detecting th

**Comment by bpinto** [comment]
Want to play safe? Instead of overwriting, append.

**Comment by bpinto** [comment]
For clarity: Append to the backup file.

**Comment by bobthecow** [comment]
Ewww. No. Just fail and let the user know what happened :)

**Comment by bpinto** [comment]
I don't like halting a installation because of backup files. As I said above, I don't think this is necessary. Perhaps we should close this issue then?

**Comment by bucaran** [comment]
Close :+1:

**Comment by bpinto** [comment]
2 x 1! :P

**Comment by bobthecow** [comment]
I don't like overwriting users' files without notice and without any way to stop it. But maybe I'm weird that way :)
