### ISSUE TITLE
Redirection does not work sometimes. Like if it's rainy or cloudy.

### ISSUE THREAD

**Issue by bucaran** [bpinto/oh-my-fish#450]
After I upgraded to fish 2.1.2-1280, `bobthefish` fails to fully redirect to `/null` with

```fish
if type rvm-prompt > /dev/null
```

It does work if you add ` ^/dev/null`

@bobthecow PR?

May be related to [this](https://github.com/fish-shell/fish-shell/issues/1674).

**Comment by bucaran** [comment]
Nevermind, it was a problem with oh-my-fish. Now it's gone.

**Comment by bobthecow** [comment]
Was the problem that you hadn't updated recently? ;)

https://github.com/bpinto/oh-my-fish/commit/d87760e34c2e4aa5d0940dc49f851677ca505446

**Comment by bucaran** [comment]
Yup! :p
