### ISSUE TITLE
Support custom completions

### ISSUE THREAD

**Issue by nirvdrum** [bpinto/oh-my-fish#457]
It would be nice if in addition to custom plugins, custom completions were supported.  I'm currently doing this by adding a file named `~/.oh-my-fish/custom/oh-my-fish-extensions.load`, which contains:

```
set -x fish_complete_path $fish_custom/completions $fish_complete_path
```

I tried to use `_prepend_path`, but I couldn't get the changes to persist.  I can also look at doing a pull request.  I have an idea of where to do it, but since this is core I'd appreciate a bit of guidance on where you'd like the change made.

**Comment by bucaran** [comment]
Support for completions exists via creating a directory named `completions` inside the plugins directory and in that directory having a file of the same name of the plugin with the completion definitions.

Please have a look at `import`:
https://github.com/bpinto/oh-my-fish/blob/master/functions/import.fish

**Comment by bobthecow** [comment]
For your own local completions, if they're not plugin-related, you can also use the Fish default `~/.config/fish/completions` folder.

**Comment by nirvdrum** [comment]
@bucaran I tried that initially and it didn't work.  Looking at the file you linked, it looks like maybe this is a bug in `import`.  The definition is missing a line to look in `$fish_custom/$library/completions`.  If I add the following:

```
_prepend_path $fish_custom/$library/completions -d fish_complete_path
```

things work the way I expect.

**Comment by nirvdrum** [comment]
@bobthecow While certainly an option, I have all of my fish config version-controlled in my .oh-my-fish custom directory.  I'd hate to split this over two repositories.

**Comment by bobthecow** [comment]
Just add a plugin then. Mine are in a plugin called `custom-completions`.

**Comment by nirvdrum** [comment]
You guys both seem to be able to successfully load custom completions.  I'm not sure what I'm doing wrong.  But I did up a pull request that fixes the problem as I understand it.  And without my proposed fix, the spec does fail.

PR is at #458.

**Comment by bucaran** [comment]
Closing this in favor of #458

**Comment by bobthecow** [comment]
Yeah, I think you're right. As I recall, at one point they worked, but I'd moved all my custom completions into `.config/fish` a while ago, so I didn't notice that `custom/$library/completions` stopped working.
