### ISSUE TITLE
Invalid index value when installing oh my fish

### ISSUE THREAD

**Issue by Moeryn** [bpinto/oh-my-fish#459]
I wanted to try oh my fish but during installation I had some errors.

    curl -L https://github.com/bpinto/oh-my-fish/raw/master/tools/install.fish | fish
     fish: Invalid index value
     /home/moeryn/.oh-my-fish/functions/_prepend_tree.fish (line 67):     for option in $argv[3..-1]
                                                                                        ^
    in function “_prepend_tree”,
    	called on line 38 of file “/home/moeryn/.oh-my-fish/functions/import.fish”,
    	with parameter list “/home/moeryn/.oh-my-fish/plugins/theme *.fish -a ! *.spec.fish”

    in function “import”,
	called on line 24 of file “/home/moeryn/.oh-my-fish/oh-my-fish.fish”,
	with parameter list “plugins/theme themes/robbyrussell”

    in . (source) call of file “/home/moeryn/.oh-my-fish/oh-my-fish.fish”,
	called on line 16 of file “/home/moeryn/.config/fish/config.fish”,

    in . (source) call of file “/home/moeryn/.config/fish/config.fish”,
	called on standard input,

**Comment by bpinto** [comment]
What version of fish are you running?

**Comment by Moeryn** [comment]
1.23.1

**Comment by bucaran** [comment]
That one is pretty old.

You should be something like `2.1.2-1280-gcec1dc2`

**Comment by Moeryn** [comment]
I installed it with this command:

    curl -L https://github.com/bpinto/oh-my-fish/raw/master/tools/install.fish | fish

**Comment by bucaran** [comment]
I mean you need to update `fish` the shell.
http://fishshell.com/files/2.1.2/fish.pkg

**Comment by Moeryn** [comment]
@bucaran I deleted my last post as it was wrong.

It installed fish using the standard procedure for Debian 7, it turns out the version is 1.23.1.
I compiled fish-shell directly from the repository and now I manage to make om-my-fish work.

Thanks for your help

**Comment by bucaran** [comment]
:+1: Good to know.
