### ISSUE TITLE
(23) Failed writing body - on installation.

### ISSUE THREAD

**Issue by bobclewell** [bpinto/oh-my-fish#464]
I have fish installed, but when I try to install oh-my-fish I see errors.

```
fish > curl -L https://github.com/bpinto/oh-my-fish/raw/master/tools/install.fish | fish
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   143    0   143    0     0    558      0 --:--:-- --:--:-- --:--:--   558
100  5099  100  5099    0     0   8885      0 --:--:-- --:--:-- --:--:--  8885
(23) Failed writing body
```

**Comment by bpinto** [comment]
What version of fish do you have installed?

**Comment by bobclewell** [comment]
2.1.2

**Comment by bucaran** [comment]
[This came up](http://stackoverflow.com/questions/16703647/why-curl-return-and-error-23-failed-writing-body) when I googled "Failed writing body".

In bash you usually wrap everything in a function to assure the script only runs after the whole file is downloaded. I am not sure about fish in this point.

@bobclewell There's no harm in asking, so, can you try curling again?

**Comment by bobclewell** [comment]
Retried ```curl``` same result.  So is the fix to just download the file and run manually? 

And is it something about my setup that breaks it or is the script broken in general?

**Comment by bpinto** [comment]
@bobclewell What about this other curl?
`curl -L https://github.com/bpinto/oh-my-fish/raw/master/tools/install.fish | cat - /dev/null | fish`

**Comment by bobclewell** [comment]
No error with that command, but the install script didn't run either. 
```
> curl -L https://github.com/bpinto/oh-my-fish/raw/master/tools/install.fish | cat - /dev/null | fish
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   143    0   143    0     0    478      0 --:--:-- --:--:-- --:--:--   479
100  5099  100  5099    0     0   8609      0 --:--:-- --:--:-- --:--:--  8609
```

I don't see a ```config.orig``` file.

**Comment by bucaran** [comment]
Something about your OS configuration?

**Comment by bpinto** [comment]
Would you join https://gitter.im/bpinto/oh-my-fish?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge ?

**Comment by bobclewell** [comment]
I had an alias for ```fish```. Removing it fixed the issue.

```
alias fish="cd ~/.config/fish/"
```
