### ISSUE TITLE
Add Fedora plugin

### ISSUE THREAD

**Issue by Poorchop** [bpinto/oh-my-fish#466]
I ported my favorite Fedora plugin for zsh to fish. It functions similarly to the exiting archlinux plugin in that it just provides simple package manager aliases. The source repo doesn't have a license, but I credited the author in the README, so hopefully that should suffice.

[Link to the fish plugin in my fork](https://github.com/Poorchop/oh-my-fish/tree/fedora-plugin/plugins/fedora)

**Comment by bucaran** [comment]
Thanks. You have to open a PR.

**Comment by Poorchop** [comment]
I was going to open a PR but the guidelines for contributing were a little tricky. It says to open a new issue linking to your repo and then I guess one of the organization members adds the requested changes if they pass inspection. I'll go ahead and open a PR though.

**Comment by bpinto** [comment]
Hey @Poorchop sorry for the confusion.
We have just (yesterday) enabled support for external plugins, so the README is not perfect yet. We will improve it, if you have an idea of how to improve, that would be great.
