### ISSUE TITLE
Dependency between plugins

### ISSUE THREAD

**Issue by leira** [bpinto/oh-my-fish#88]
To import a dependent plugin from another plugin is useful sometimes, oh-my-zsh has this feature, seems oh-my-fish has not implemented it yet.

**Comment by bucaran** [comment]
#280 and #284 should fix and allow simple plugin interdependency.

#280: Adds `prepend_tree` that basically traverses a source path and prepends each directory matching a list of glob patterns to a destination path (leave out to to add them to `fish_function_path`.

#284: Automatically sources completion and `load` files when `_fish_add_plugin` is called.

_prepend_tree (dirname $argv) # Source dependencies inside current plugin.
_fish_add_plugin # Adds plugin and calls that plugins `plugin.load`.

`_fish_add_plugin` calls `_prepend_tree` behind the scenes which checks whether the path to add already exists in the destination path, saving you the trouble to check for conflicting imports.

**Comment by bpinto** [comment]
There is a new [import](https://github.com/bpinto/oh-my-fish/blob/master/functions/import.fish) function that allows plugins and themes to depend on other plugins.

Ping @leira
