### ISSUE TITLE
Load plugins in background

### ISSUE THREAD

**Issue by fazibear** [bpinto/oh-my-fish#96]
Hey, 

Where I have lot of plugins I need to wait until they load, what about idea to load it in background ?

for example:

set fish_plugins node brew fry-plugin rake& bundler&

rake and bundler plugins were load in background, after prompt appeared.

Is this possible ?

**Comment by bucaran** [comment]
Here is a little bit of an idea using @bobthecow `tab` plugin:

```
function background -a done_handler
  tab # Open a new terminal tab in iTerm2 or Terminal (creates a new fish session).


  for i in (seq 1 50000)
    echo Loading a bunch of dependencies \#x00$i
  end
  echo OK
  # echo $fish_function_path
  # set -U fish_function_path $fish_function_path \
  #   $fish_path/custom/plugins/mylib

  set -U ___para 100

end
```

**Comment by bpinto** [comment]
We would need to either use universal variables or redo the env changes on the main session. I am afraid this wouldn't be feasible or worth it.

**Comment by bucaran** [comment]
We should close this issue as it seems like something that will not be fixed in the near future or at all.

**Comment by bpinto** [comment]
I guess you are right, as much as I would like to get this done, I don't think this will ever be possible.
